function TG100119720230815T010000 = ReadLI7810(filename, dataLines)
%IMPORTFILE Import data from a text file
%  TG100119720230815T010000 = IMPORTFILE(FILENAME) reads data from text
%  file FILENAME for the default selection.  Returns the data as a table.
%
%  TG100119720230815T010000 = IMPORTFILE(FILE, DATALINES) reads data for
%  the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  TG100119720230815T010000 = importfile("C:\Users\johnc\Desktop\Research\Chamber_Processing\Data\Trip08152023\TG10-01197-2023-08-15T010000.data", [7, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 28-Aug-2023 12:50:01

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [7, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 22);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["DATAH", "SECONDS", "NANOSECONDS", "NDX", "DIAG", "REMARK", "DATE", "TIME", "H2O", "CO2", "CH4", "CAVITY_P", "CAVITY_T", "LASER_PHASE_P", "LASER_T", "RESIDUAL", "RING_DOWN_TIME", "THERMAL_ENCLOSURE_T", "PHASE_ERROR", "LASER_T_SHIFT", "INPUT_VOLTAGE", "CHK"];
opts.VariableTypes = ["categorical", "double", "double", "double", "double", "string", "datetime", "datetime", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "REMARK", "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["DATAH", "REMARK"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "DATE", "InputFormat", "yyyy-MM-dd");
opts = setvaropts(opts, "TIME", "InputFormat", "HH:mm:ss");

% Import the data
TG100119720230815T010000 = readtable(filename, opts);

end