---
title: "Ecosys"
author: "Erin Hassett"
date: "11/4/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---
#load libararies
```{r setup, include=FALSE}
#these data are plant and open cells from Ecosys, simulated in the CHANNEL only. 

getwd()
setwd("C:/Erin/ecosys/Channel/Channel_CH4_FINAL")

library(ggplot2)
library(magrittr)
library(ggpubr)
library(lubridate)
#library (tidyverse)
library(hydroGOF) #rmse
library(readr)
```
#bOA parameters
```{r}
trials_ch4 <- read.csv("trial_parameters_ch4.csv")
trials_co2 <- read.csv("trial_parameters_co2.csv")
last30<- tail(trials_ch4,30)
mean30 <- colMeans(last30)

p1a <- ggplot(trials_ch4, aes(x = seq_along(VMXC), y = VMXC)) +
  geom_line() + ggtitle("Hydrogenotrophic Methanogens") +
  ylab("Oxidation rate(g C g-1 C h-1)") + xlab("Trial")+
  theme(plot.title=element_text(hjust=0.5),
        axis.title.x=element_blank())

p2a <- ggplot(trials_ch4, aes(x = seq_along(VMX4), y = VMX4)) +
  geom_line() + ggtitle("Methanotrophs") +
  ylab("Oxidation rate(g C g-1 C h-1)") + xlab("Trial")+
  theme(plot.title=element_text(hjust=0.5),
        axis.title.y=element_blank(),
        axis.title.x=element_blank())

p3a <- ggplot(trials_ch4, aes(x = seq_along(VMXM), y = VMXM)) +
  geom_line() + ggtitle("Acetotrophic Methanogens") +
  ylab("Oxidation rate(g C g-1 C h-1)") + xlab("Trial")+
  theme(plot.title=element_text(hjust=0.5))

p4a <- ggplot(trials_ch4, aes(x = seq_along(VMXF), y = VMXF)) +
  geom_line() + ggtitle("Fungi") +
  ylab("Oxidation rate (g C g-1 C h-1)") + xlab("Trial")+
  theme(plot.title=element_text(hjust=0.5),
        axis.title.y=element_blank())

ggarrange(p1a,p2a,p3a,p4a, nrow=2, ncol=2)

#Channel CO2
p1 <- ggplot(trials_co2, aes(x = seq_along(rubcarb), y = rubcarb)) +
  geom_line() + ggtitle("Rubisco Carboxylation") +
  ylab("µmol g⁻¹ s⁻¹") + xlab("Trial")

p2 <- ggplot(trials_co2, aes(x = seq_along(rubox), y = rubox)) +
  geom_line() + ggtitle("Rubisco Oxygenation") +
  ylab("µmol g⁻¹ s⁻¹") + xlab("Trial")

p3 <- ggplot(trials_co2, aes(x = seq_along(shortalb), y = shortalb)) +
  geom_line() + ggtitle("Shortwave Albedo") +
  ylab("%") + xlab("Trial")

p4 <- ggplot(trials_co2, aes(x = seq_along(paralb), y = paralb)) +
  geom_line() + ggtitle("PAR Albedo") +
  ylab("%") + xlab("Trial")

p5 <- ggplot(trials_co2, aes(x = seq_along(rootpor), y = rootpor)) +
  geom_line() + ggtitle("Root Porosity") +
  ylab("m³/m³") + xlab("Trial")

p6 <- ggplot(trials_co2, aes(x = seq_along(leafon), y = leafon)) +
  geom_line() + ggtitle("Leaves On") +
  ylab("Hours in the Year") + xlab("Trial")

p7 <- ggplot(trials_co2, aes(x = seq_along(leaffoff), y = leaffoff)) +
  geom_line() + ggtitle("Leaf Off") +
  ylab("Hours in the Year") + xlab("Trial")

ggarrange(p1, p2, p3, p4, p5, p6, p7, nrow = 3, ncol = 3)



h1 <- ggplot(trials_ch4, aes( x = VMXC)) +
  geom_histogram() + ggtitle("Hydrogenotrophic Methanogens") +
  xlab("Oxidation rate(g C g⁻¹ C h⁻¹)") + ylab("Frequency")+
  theme_bw()+
  theme(plot.title=element_text(hjust=0.5),
        axis.title.x=element_blank())

h2 <- ggplot(trials_ch4, aes(x = (VMX4))) +
  geom_histogram() + ggtitle("Methanotrophs") +
  xlab("Oxidation rate(g C g⁻¹ C h⁻¹)") + ylab("Freequency")+
    theme_bw()+
  theme(plot.title=element_text(hjust=0.5),
        axis.title.y=element_blank(),
        axis.title.x=element_blank())

h3 <- ggplot(trials_ch4, aes(x = VMXM)) +
  geom_histogram() + ggtitle("Acetotrophic Methanogens") +
  xlab("Oxidation rate(g C g⁻¹ C h⁻¹)") + ylab("Freequency")+
    theme_bw()+
  theme(plot.title=element_text(hjust=0.5))

h4 <- ggplot(trials_ch4, aes(x = VMXF)) +
  geom_histogram() + ggtitle("Fungi") +
  xlab("Oxidation rate (g C g⁻¹ C h⁻¹)") + ylab("Frequency")+
    theme_bw()+
  theme(plot.title=element_text(hjust=0.5),
        axis.title.y=element_blank())

ggarrange(h1,h2,h3,h4, nrow=2, ncol=2)

#Channel CO2
h5 <- ggplot(trials_co2, aes(x = (rubcarb))) +
  geom_histogram() + ggtitle("Rubisco Carboxylation") +
  xlab("µmol g⁻¹ s⁻¹") + ylab("Frequency")+
    theme_bw()+
  theme(plot.title=element_text(hjust=0.5))
       # axis.title.y=element_blank())

h6 <- ggplot(trials_co2, aes(x = rubox)) +
  geom_histogram() + ggtitle("Rubisco Oxygenation") +
  xlab("µmol g⁻¹ s⁻¹") + ylab("frequency")+
  theme_bw()+
  theme(plot.title=element_text(hjust=0.5),
        axis.title.y=element_blank())

h7 <- ggplot(trials_co2, aes(x = shortalb)) +
  geom_histogram() + ggtitle("Shortwave Albedo") +
  xlab("%") + ylab("frequency")+
    theme_bw()+
  theme(plot.title=element_text(hjust=0.5),
        axis.title.y=element_blank())

h8 <- ggplot(trials_co2, aes(x = paralb)) +
  geom_histogram() + ggtitle("PAR Albedo") +
  xlab("%") + ylab("Frequency")+
    theme_bw()+
  theme(plot.title=element_text(hjust=0.5))
       # axis.title.y=element_blank())

h9 <- ggplot(trials_co2, aes(x = (rootpor))) +
  geom_histogram() + ggtitle("Root Porosity") +
  xlab("m³/m³") + ylab("Frequency")+
    theme_bw()+
  theme(plot.title=element_text(hjust=0.5),
        axis.title.y=element_blank())

h10 <- ggplot(trials_co2, aes(x = leafon)) +
  geom_histogram() + ggtitle("Leaves On") +
  xlab("Hours in the Year") + ylab("Frequency")+
    theme_bw()+
  theme(plot.title=element_text(hjust=0.5),
        axis.title.y=element_blank())

h11 <- ggplot(trials_co2, aes(x = leaffoff)) +
  geom_histogram() + ggtitle("Leaf Off") +
  xlab("Hours in the Year") + ylab("Frequency")+
    theme_bw()+
  theme(plot.title=element_text(hjust=0.5))
       # axis.title.y=element_blank())

ggarrange(h5, h6, h7, h8, h9, h10, h11, nrow = 3, ncol = 3)
```
#make all 1 file
```{r}
years <- c(2015,2020,2021,2022,2023)
plant_prefix <- "02010"
nonplant_prefix <- "03010"
directory <-setwd("C:/Erin/ecosys/Channel/Channel_CH4_FINAL")

all_plant <- list()
all_nonplant <- list()

for (year in years) {
  # Read plant file
  plant_file <- paste0(plant_prefix, year, "hc")
  plant_path <- file.path(directory, plant_file)  
  if (file.exists(plant_path)) {
    plant <- read.table(plant_path, quote = "\"", comment.char = "", stringsAsFactors = FALSE)
    names(plant) <- plant[1, ]
    plant <- plant[-1, ]
    plant$Year <- year
    all_plant[[as.character(year)]] <- plant
  }
  
  # Read non-plant file
  nonplant_file <- paste0(nonplant_prefix, year, "hc")
  nonplant_path <- file.path(directory, nonplant_file)
  if (file.exists(nonplant_path)) {
    nonplant <- read.table(nonplant_path, quote = "\"", comment.char = "", stringsAsFactors = FALSE)
    names(nonplant) <- nonplant[1, ]
    nonplant <- nonplant[-1, ]
    nonplant$Year <- year
    all_nonplant[[as.character(year)]] <- nonplant
  }
}

# Combine all years for each
plant_df <- bind_rows(all_plant)
nonplant_df <- bind_rows(all_nonplant)

# Convert numeric columns
plant_df <- plant_df %>%
  mutate(across(c(ECO_CO2_FLUX, CH4_FLUX), as.numeric))
plant_df <- plant_df %>%
  select(DOY, DATE, HOUR, ECO_CO2_FLUX, CH4_FLUX)
plant_df$DATE <- dmy(plant_df$DATE)
plant_df$Month <- month(plant_df$DATE)
plant_df <- plant_df %>%
  mutate(Year = year(DATE),
         Month2 = month.name[Month])
plant_df$MonthYear <- factor(
  paste(plant_df$Year, plant_df$Month2, sep = "-"),
  levels = unique(paste(plant_df$Year, plant_df$Month2, sep = "-")))

nonplant_df <- nonplant_df %>%
  mutate(across(c(ECO_CO2_FLUX, CH4_FLUX), as.numeric))
nonplant_df <- nonplant_df %>%
  select(DOY, DATE, HOUR, ECO_CO2_FLUX, CH4_FLUX)
nonplant_df$DATE <- dmy(nonplant_df$DATE)
nonplant_df$Month <- month(nonplant_df$DATE)
nonplant_df <- nonplant_df %>%
  mutate(Year = year(DATE),
         Month2 = month.name[Month])
nonplant_df$MonthYear <- factor(
  paste(nonplant_df$Year, nonplant_df$Month2, sep = "-"),
  levels = unique(paste(nonplant_df$Year, nonplant_df$Month2, sep = "-")))

plant_df <- plant_df %>%
  mutate(HOUR = factor(as.character(HOUR),
                 levels = c("1","2", "3","4", "5","6","7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17","18", "19","20", "21", "22", "23","24")))

nonplant_df <- nonplant_df %>%
  mutate(HOUR = factor(as.character(HOUR),
                 levels = c("1","2", "3","4", "5","6","7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17","18", "19","20", "21", "22", "23","24")))
# Save result
#write_csv(merged, "raw_flux_wide_format.csv")

# Merge both by common columns (e.g., Year, Date, Hour — adjust as needed)
full <- full_join(
  plant_df, 
  nonplant_df, 
  by = c("DOY", "DATE", "HOUR"), 
  suffix = c("_Plant", "_NonPlant")
)
#str(full)
#full$DATE <- dmy(full$DATE)
full$HOUR <- as.numeric(full$HOUR)
plot(full$CH4_FLUX_Plant, main= "Plant")
plot(full$CH4_FLUX_NonPlant, main="Non Plant")

#ADD IN FOOTPRINT
footprint <- read_csv("footprint_all.csv",show_col_types = FALSE)
footprint$TIMESTAMP <- ymd_hm(footprint$TIMESTAMP)
footprint[footprint == -9999] <- NA

#plot(footprint$Plants, ylim = c(1.1,20))

footprint_hourly <- footprint %>%
  mutate(TIMESTAMP2 = floor_date(TIMESTAMP, unit = "hour")) %>%
  group_by(TIMESTAMP2) %>%
  summarise(across(c(Outside, Forest, Plants, Water), ~ mean(.x, na.rm = TRUE))) %>%
  ungroup()

footprint_hourly <- footprint_hourly %>%
  mutate(
    DATE = as.Date(TIMESTAMP2),
    HOUR = hour(TIMESTAMP2),
    HOUR = ifelse(HOUR == 0, 24, HOUR))

full2 <- full_join(
  full, 
  footprint_hourly, 
  by = c("DATE", "HOUR"))

full2$ECO_CO2_FLUX = ((full2$ECO_CO2_FLUX_Plant*full2$Plants)+(full2$ECO_CO2_FLUX_NonPlant* full2$Water))*-1
full2$CH4_FLUX = ((full2$CH4_FLUX_Plant*full2$Plants)+(full2$CH4_FLUX_NonPlant*full2$Water))*-1

full2[] <- lapply(full2, function(x) {
  if (is.numeric(x)) x[is.nan(x)] <- NA
  return(x)
})


df_means_plant <- full2 %>%
  mutate(
    DATE = as.Date(DATE),
    Year = year(DATE),
    Month = month(DATE)
  ) %>%
  filter(
    Month %in% 5:10,
    Year %in% c(2022, 2023) #compare to chamber years
  ) %>%
  group_by(Year) %>%
  summarise(
    n_CO2 = sum(!is.na(ECO_CO2_FLUX_Plant)),
    n_CH4 = sum(!is.na(CH4_FLUX_Plant)),
    mean_ECO_CO2_Flux = (ifelse(n_CO2 > 0, mean(ECO_CO2_FLUX_Plant, na.rm = TRUE), NA))*-1,
    mean_CH4_Flux     = (ifelse(n_CH4 > 0, mean(CH4_FLUX_Plant, na.rm = TRUE), NA))*-1,
    .groups = "drop"
  )


#read in real data and merge with modeled data
obs <- read_csv("obs_data.csv",show_col_types = FALSE)
obs$DATE <-mdy(obs$DATE)
merged_full <- merge(full2, obs, by = c( "DATE","HOUR"), all = TRUE) 

#merged_full <- merged_full %>% filter(HOUR %in% (9:16) )
merged_full2 <- merged_full %>%
  filter(Month_Plant >= 5 & Month_Plant <= 10)%>% 
  group_by(Year_Plant,Month_Plant,MonthYear_Plant,HOUR) %>% 
  summarise(AMF_CO2 = mean(AMF_FC, na.rm = T), AMF_FCH4 = mean(AMF_FCH4, na.rm = T), CO2 = mean(ECO_CO2_FLUX, na.rm = T), CH4 = mean(CH4_FLUX, na.rm = T ))

rmse(merged_full2$AMF_FCH4,merged_full2$CH4)
rmse(merged_full2$AMF_CO2,merged_full2$CO2)

# Function to calculate standard error
se <- function(x) sd(x, na.rm = TRUE) / sqrt(sum(!is.na(x)))

merged_short <- merged_full %>%
filter(year(TIMESTAMP2) %in% c(2015, 2020,2021,2022,2023)) %>%
  mutate(Year = factor(year(TIMESTAMP2)))

df_medians <- merged_short %>%
  mutate(Year = year(as.Date(DATE))) %>%
  group_by(Year) %>%
  summarise(
    median_ECO_CO2_Flux = median(ECO_CO2_FLUX, na.rm = TRUE),
    median_CH4_Flux = median(CH4_FLUX, na.rm = TRUE))

df_means <- merged_short %>%
  mutate(
    DATE = as.Date(DATE),
    Year = year(DATE),
    Month = month(DATE)
  ) %>%
  filter(
    Month %in% 5:10,
    Year %in% c(2022, 2023) #compare to chamber years
  ) %>%
  group_by(Year) %>%
  summarise(
    n_CO2 = sum(!is.na(ECO_CO2_FLUX)),
    n_CH4 = sum(!is.na(CH4_FLUX)),
    mean_ECO_CO2_Flux = ifelse(n_CO2 > 0, mean(ECO_CO2_FLUX, na.rm = TRUE), NA),
    mean_CH4_Flux     = ifelse(n_CH4 > 0, mean(CH4_FLUX, na.rm = TRUE), NA),
    .groups = "drop"
  )

```
#plots
```{r}
CD1<-ggplot(merged_short, aes(x = TIMESTAMP2, y = AMF_FC))+
  geom_point(color = "black") +
  #geom_line(aes(y = ECO_CO2_FLUX), color = "red") +
  facet_wrap(~ Year, scales = "free_x") +
    scale_x_datetime(date_labels = "%b") +
  labs(x = "Hour", y = expression(CO[2]~flux~(mu*mol~m^-2~s^-1))) +
  theme_bw()+
  theme(text = element_text(family = "serif"),
    plot.title = element_text(hjust=0.5),
        axis.text.x = element_text(angle = 45),
     axis.title.x=element_blank())

M1<-ggplot(merged_short, aes(x = TIMESTAMP2, y = AMF_FCH4))+
  geom_point(color = "black") +
 # geom_line(aes(y = CH4_FLUX), color = "red") +
  facet_wrap(~ Year, scales = "free_x") +
    scale_x_datetime(date_labels = "%b") +
  labs(x = "Hour", y = expression(CH[4]~flux~(mu*mol~m^-2~s^-1))) +
  theme_bw()+
  theme(text = element_text(family = "serif"),
       plot.title = element_text(hjust=0.5),
        axis.text.x = element_text(angle = 45),
       axis.title.x=element_blank())
```
#Figure 3
```{r}
Figure3<-ggarrange(CD1,M1, labels="AUTO") #Figure 3
ggsave(
  "Figure3.tiff",
  plot = Figure3,
  width = 2244,
  height = 1400,
  units = "px",
  dpi = 300,
  compression = "lzw")
```
#Co2 plots
###Diurnal/hourly
```{r}
# Summarize CO2
df_CO2b <- merged_full2 %>%
  group_by(MonthYear_Plant, HOUR) %>%
  summarise(
    AMF_CO2_mean = mean(AMF_CO2, na.rm = TRUE),
    AMF_CO2_se   = se(AMF_CO2),
    CO2_mean     = mean(CO2, na.rm = TRUE),
    .groups = "drop")

# --- Collapse across years, only July–October ---
df_CO2_monthly_old <- merged_full2 %>%
  filter(Month_Plant %in% 5:10) %>% #only July–October
  group_by(Month_Plant, HOUR) %>%
  summarise(
    AMF_CO2_mean = mean(AMF_CO2, na.rm = TRUE),
    AMF_CO2_se   = sd(AMF_CO2, na.rm = TRUE) /sqrt(n()),
    CO2_mean     = mean(CO2, na.rm = TRUE),
    .groups = "drop")

df_CO2_monthly <- merged_full %>%
  filter(Month_Plant %in% 5:10) %>%
  group_by(Month_Plant, HOUR) %>%
  summarise(
    AMF_CO2_mean = mean(AMF_FC, na.rm = TRUE),
    AMF_CO2_se   = sd(AMF_FC, na.rm = TRUE) / sqrt(n()),
    CO2_mean     = mean(ECO_CO2_FLUX, na.rm = TRUE),
    CO2_se       = sd(ECO_CO2_FLUX, na.rm = TRUE) / sqrt(n()),
    .groups = "drop"
  )

# --- Label months ---
df_CO2_monthly$Month_Label <- factor(df_CO2_monthly$Month_Plant, levels = 5:10, labels = c("May","June","July", "August", "September","October"))

# FIGURE 2
CO2_HOUR <- ggplot(df_CO2_monthly, aes(x = HOUR)) +
  geom_ribbon(aes(
    ymin = AMF_CO2_mean - AMF_CO2_se,
    ymax = AMF_CO2_mean + AMF_CO2_se,
    fill = "Observed"), alpha = 0.4) +
  geom_ribbon(aes(
    ymin = CO2_mean - CO2_se,
    ymax = CO2_mean + CO2_se,
    fill = "Modeled"), alpha = 0.2) +
  geom_line(aes(y = AMF_CO2_mean, color = "Observed")) +
  geom_line(aes(y = CO2_mean, color = "Modeled")) +
  facet_wrap(~Month_Label, ncol = 2) +
  labs(
    x = "Hour",
    y = expression(CO[2]~"flux (µmol m"^-2~"s"^-1~")"),
    color = "Method",
    fill = "Standard Error") +
  scale_color_manual(
    values = c("Observed" = "black", "Modeled" = "red")) +
  scale_fill_manual(
    values = c("Observed" = "grey40", "Modeled" = "red")) +
  theme_bw() +
  theme(text = element_text(family = "serif", size=9),
        legend.position = "right",
        strip.background = element_blank(),
        strip.text = element_text(size = 9),
        panel.spacing = unit(0.4, "lines"),
        plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust=0.5))

# Average by DAY
dfCO2_clean <- merged_full %>%
  mutate(
  Day = yday(DATE)) %>%
  group_by(Year_Plant, Day) %>%
  filter(!is.na(Year_Plant)) %>%
  summarise(
    CO2_FLUX = mean(ECO_CO2_FLUX, na.rm = TRUE),
    AMF_CO2  = mean(AMF_FC,  na.rm = TRUE),
    Date_day = first(as.Date(DATE))) %>% ungroup()

```
##co2 model: 2015-2023
```{r}
# Fit regression model with hourly data frame
co2model1 <- lm(ECO_CO2_FLUX~AMF_FC, data = merged_full)
summary(co2model1)
# Extract slope and R2
coef(co2model1)
co2slope1 <- coef(co2model1)[2]
co2intercept1 <- coef(co2model1)[1] # not used
co2r21 <- summary(co2model1)$r.squared

obs<-merged_full$AMF_FC
mod <-merged_full$ECO_CO2_FLUX

valid <- complete.cases(obs, mod)
obs <- obs[valid]
mod <- mod[valid]

# Compute metrics
RMSE  <- sqrt(mean((mod - obs)^2))
Bias  <- mean(mod - obs)
Slope <- coef(lm(mod ~ obs))[2]
R2    <- summary(lm(mod ~ obs))$r.squared

# Print
cat("RMSE =", round(RMSE, 3), "\n")
cat("Bias =", round(Bias, 3), "\n")
cat("Slope =", round(Slope, 3), "\n")
cat("R² =", round(R2, 3), "\n")

# ONE line for ALL years
MODEL1<-ggplot(merged_full, aes(x = AMF_FC, y = ECO_CO2_FLUX, colour = Year_NonPlant)) + 
  geom_point() +
  xlim(-20, 20) +
  ylim(-20, 20) +
  geom_smooth(method = "lm", se = FALSE, color = "black") +
  geom_abline(slope = 1, intercept = 0, color = "red", linetype = "dashed",size=0.8) +
  theme_bw() +
  theme(text = element_text(family = "Times New Roman"),
    axis.text.x = element_text(hjust = 1),
    plot.title = element_text(hjust = 0.5)
  ) +
  labs(
    x = expression(CO[2]~"flux (µmol m"^-2~"s"^-1~") Observed"),
    y = expression(CO[2]~"flux (µmol m"^-2~"s"^-1~") Modeled"),
   # title = "Carbon Dioxide 2015-2023",
    color = "Year",
    fill = "Year"
  ) +
  annotate(
    "text",
    x = Inf, y = -Inf, hjust = 1.1, vjust = -0.5,
    label = paste0("Slope = ", round(co2slope1, 2),
                   "\nR² = ", round(co2r21, 2))
  )

# Fit regressions for each year/ with hourly data
#merged_full2$Year_Plant<-as.factor(merged_full2$Year_Plant)

# Fit regressions per year 
reg_stats1 <- merged_full %>%
  group_by(Year_Plant) %>%
  group_modify(~ {
    data_sub <- .x %>% filter(!is.na(ECO_CO2_FLUX), !is.na(AMF_FC))
    if (nrow(data_sub) > 1) {
      co2model_H <- lm(AMF_FC ~ ECO_CO2_FLUX, data = data_sub)
      tibble(
        slope = coef(co2model_H)[[2]],
        r2    = summary(co2model_H)$r.squared)} 
    else {tibble(slope = NA_real_, r2 = NA_real_)}})

# Place labels near top-right of each facet/group
label_datab <- merged_full %>%
  group_by(Year_Plant) %>%
  summarise(
    x = max(ECO_CO2_FLUX, na.rm = TRUE),
    y = max(AMF_FC, na.rm = TRUE)) %>%
  left_join(reg_stats1, by = "Year_Plant") %>%
  mutate(
    label = paste0("Slope = ", round(slope, 2), ", R² = ", round(r2, 2)),
   x = -10, 
   y = seq( from = 5, by = 1.5, 
            length.out = n()))

# Plot, slope/R2 separated by YEAR
ggplot(merged_full, aes(x = ECO_CO2_FLUX, y = AMF_FC, colour = as.factor(Year_Plant))) +
  geom_point(alpha = 0.6) +
  geom_smooth(method = "lm", se = FALSE, aes(color = as.factor(Year_Plant))) +
  geom_text(
    data = label_datab,
    aes(x = x, y = y, label = label, colour = as.factor(Year_Plant)),
    hjust = 0, vjust = 0, show.legend = FALSE
  ) +
  theme_bw() +
  labs(
    x = expression(CO[2]~"flux (µmol m"^-2~"s"^-1~") Modeled"),
    y = expression(CO[2]~"flux (µmol m"^-2~"s"^-1~") Observed"),
    title = "Carbon Dioxide in Main Wetland (Hourly)",
    color = "Year"
  ) +
  theme(plot.title = element_text(hjust = 0.5))


#2016-2023

merged_2020 <-merged_full %>%
filter(year(DATE) %in% c(2020,2021,2022,2023)) %>%
  mutate(Year = factor(year(DATE)))

co2mod_2020 <- lm(ECO_CO2_FLUX~AMF_FC, data = merged_2020)
#summary(co2mod_2020)
# Extract slope and R2
#coef(co2mod_2020)
#co2slope20 <- coef(co2mod_2020)[2]
#co2intercept20 <- coef(co2mod_2020)[1] # not used
#co2r2_20 <- summary(co2mod_2020)$r.squared
obs2<-merged_2020$AMF_FC
mod2 <-merged_2020$ECO_CO2_FLUX
valid2 <- complete.cases(obs2, mod2)
obs2 <- obs2[valid2]
mod2 <- mod2[valid2]
# Compute metrics
RMSE2  <- sqrt(mean((mod2 - obs2)^2))
Bias2  <- mean(mod2 - obs2)
Slope2 <- coef(lm(mod2 ~ obs2))[2]
R2_2020    <- summary(lm(mod2 ~ obs2))$r.squared

# Print
cat("RMSE =", round(RMSE2, 3), "\n")
cat("Bias =", round(Bias2, 3), "\n")
cat("Slope =", round(Slope2, 3), "\n")
cat("R² =", round(R2_2020, 3), "\n")

# ONE line for ALL years- Figure 5
MODEL2<-ggplot(merged_2020, aes(x = AMF_FC, y = ECO_CO2_FLUX, colour = Year_NonPlant)) + 
  geom_point() +
  xlim(-15, 15) +
  ylim(-15, 15) +
  geom_smooth(method = "lm", se = FALSE, color = "black") +
  geom_abline(slope = 1, intercept = 0, color = "red", linetype = "dashed",size=0.8) +
  theme_bw() +
  theme(text = element_text(family = "Times New Roman"),
    axis.text.x = element_text(hjust = 1),
    plot.title = element_text(hjust = 0.5)) +
  labs(
    x = expression(CO[2]~"flux (µmol m"^-2~"s"^-1~") Observed"),
    y = expression(CO[2]~"flux (µmol m"^-2~"s"^-1~") Modeled"),
   # title = "Carbon Dioxide 2020-2023",
    color = "Year",
    fill = "Year") +
  annotate(
    "text",
    x = Inf, y = -Inf, hjust = 1.1, vjust = -0.5,
    label = paste0("Slope = ", round(Slope2, 2),
                   "\nR² = ", round(R2_2020, 2)))

```
# CH4 plot
##Diurnal/Hourly
```{r}
# Summarize CH4
df_CH4 <- merged_full2 %>%
  group_by(MonthYear_Plant, HOUR) %>%
  summarise(
    AMF_CH4_mean = mean(AMF_FCH4, na.rm = TRUE), 
    AMF_CH4_se   = se(AMF_FCH4),
    CH4_mean     = mean(CH4, na.rm = TRUE), 
    .groups = "drop")

# --- Collapse across years, only July–October ---
df_CH4_monthly_old <- merged_full2 %>%
  filter(Month_Plant %in% 5:10) %>% 
  group_by(Month_Plant, HOUR) %>%
  summarise(
    AMF_CH4_mean = mean(AMF_FCH4, na.rm = TRUE),
    AMF_CH4_se   = sd(AMF_FCH4, na.rm = TRUE) / sqrt(n()),
    CH4_mean     = mean(CH4, na.rm = TRUE),
    .groups = "drop")

df_CH4_monthly <- merged_full %>%
  filter(Month_Plant %in% 5:10) %>% 
  group_by(Month_Plant, HOUR) %>%
  summarise(
    AMF_CH4_mean = mean(AMF_FCH4, na.rm = TRUE),
    AMF_CH4_se   = sd(AMF_FCH4, na.rm = TRUE) / sqrt(n()),
    CH4_mean     = mean(CH4_FLUX, na.rm = TRUE),
    CH4_se       = sd(CH4_FLUX, na.rm = TRUE) / sqrt(n()),
    .groups = "drop")

p_CH4 <- ggplot(df_CH4, aes(x = HOUR)) +
  geom_ribbon(aes(ymin = AMF_CH4_mean - AMF_CH4_se,
                  ymax = AMF_CH4_mean + AMF_CH4_se,
                  fill = "AMF CH4"), alpha = 0.5) +
  geom_line(aes(y = AMF_CH4_mean, color = "AMF CH4")) +
  geom_line(aes(y = CH4_mean, color = "Observed CH4")) +
  
  facet_wrap(~MonthYear_Plant, scales = "free_y", ncol = 6) +
  labs(x = "Hour",
       y = expression(CH[4]~"flux (µmol m"^-2~"s"^-1),
      # title = "Methane in Channel",
       color = "Source",   # legend title for lines
       fill = "Source") +  # legend title for ribbon
  scale_color_manual(values = c("AMF CH4" = "black", "Observed CH4" = "red")) +
  scale_fill_manual(values = c("AMF CH4" = "grey30")) +
  theme_bw() +
  theme(text = element_text(family = "Times New Roman"),
    strip.background = element_blank(),
        strip.text = element_text(size = 10),
        panel.spacing = unit(0.4, "lines"))

# --- Label months ---
df_CH4_monthly$Month_Label <- factor(df_CH4_monthly$Month_Plant,
       levels = 5:10, labels = c("May","June","July", "August", "September","October"))

# --- Plot ---
CH4_HOUR <- ggplot(df_CH4_monthly, aes(x = HOUR)) +
  # Observed SE ribbon
  geom_ribbon(aes(
    ymin = AMF_CH4_mean - AMF_CH4_se,
    ymax = AMF_CH4_mean + AMF_CH4_se,
    fill = "Observed"), alpha = 0.4) +
  # Modeled SE ribbon
  geom_ribbon(aes(
    ymin = CH4_mean - CH4_se,
    ymax = CH4_mean + CH4_se,
    fill = "Modeled"), alpha = 0.2) +
  # Lines
  geom_line(aes(y = AMF_CH4_mean, color = "Observed")) +
  geom_line(aes(y = CH4_mean, color = "Modeled")) +
  facet_wrap(~Month_Label, ncol = 2) +
  labs(
    x = "Hour",
    y = expression(CH[4]~"flux (µmol m"^-2~"s"^-1~")"),
    color = "Method",
    fill = "Standard Error") +
 scale_color_manual(
    values = c("Observed" = "black", "Modeled" = "red") ) +
  scale_fill_manual(
    values = c("Observed" = "grey40", "Modeled" = "red")) +
  scale_y_continuous(expand = expansion(mult = 0.05)) +
  theme_bw() +
  theme(text = element_text(family = "serif", size=9),
        strip.background = element_blank(),
        strip.text = element_text(size = 9),
        panel.spacing = unit(0.4, "lines"),
        plot.title=element_text(hjust=0.5),
        plot.subtitle=element_text(hjust=0.5),
        legend.position = "right")

# Average by DAY
dfcH4_clean <- merged_full %>%
  mutate(
    Day = yday(DATE)) %>%
  group_by(Year_Plant, Day) %>%
  filter(!is.na(Year_Plant)) %>%
  summarise(
    CH4_FLUX = mean(CH4_FLUX, na.rm = TRUE),
    AMF_CH4  = mean(AMF_FCH4,  na.rm = TRUE),
    Date_day = first(as.Date(DATE))) %>%
  ungroup()

merged_full %>%
  summarise(
    ECO_CO2_FLUX_nonNA = sum(!is.na(ECO_CO2_FLUX)),
    CH4_FLUX_nonNA     = sum(!is.na(CH4_FLUX)),
    AMF_FCH4_nonNA     = sum(!is.na(AMF_FCH4)),
    AMF_FC_nonNA       = sum(!is.na(AMF_FC)))

```
#Figure 4
```{r}
Figure4<-ggarrange(CO2_HOUR, CH4_HOUR, ncol = 2, align="hv", labels="AUTO", common.legend = TRUE, legend="right")

ggsave(
  "Figure4.tiff",
  plot = Figure4,
  width = 2244,
  height = 1400,
  units = "px",
  dpi = 300,
  compression = "lzw")
```
##cH4 model
```{r}
# Fit regression model with hourly data frame
cH4model1 <- lm(CH4_FLUX ~AMF_FCH4, data = merged_full)
summary(cH4model1)
# Extract slope and R2
#coef(cH4model1)
#ch4slope1 <- coef(cH4model1)[2]
#ch4intercept1 <- coef(cH4model1)[1] # not used
#ch4r21 <- summary(cH4model1)$r.squared


obs3<-merged_full$AMF_FCH4
mod3 <-merged_full$CH4_FLUX

valid3 <- complete.cases(obs3, mod3)
obs3 <- obs3[valid3]
mod3 <- mod3[valid3]

# Compute metrics
RMSE3  <- sqrt(mean((mod3 - obs3)^2))
Bias3  <- mean(mod3 - obs3)
Slope3 <- coef(lm(mod3 ~ obs3))[2]
R2_3   <- summary(lm(mod3 ~ obs3))$r.squared

# Print
cat("RMSE =", round(RMSE3, 3), "\n")
cat("Bias =", round(Bias3, 3), "\n")
cat("Slope =", round(Slope3, 3), "\n")
cat("R² =", round(R2_3, 3), "\n")

# ONE line for ALL years #figure 5
MODEL3<-ggplot(merged_full, aes(x = AMF_FCH4, y= CH4_FLUX, colour = Year_Plant)) + #year_plant = numerical
 geom_point() +
 # xlim(-0.1,3.5)+
 geom_smooth(method = "lm",se = FALSE,color = "black")+
    geom_abline(slope = 1, intercept = 0, color = "red", linetype = "dashed", size=0.8) +
  theme_bw() +
  theme(text = element_text(family = "Times New Roman"),
    axis.text.x = element_text(hjust = 1),
        plot.title = element_text(hjust=0.5))+
  labs(x = expression(CH[4]~"flux (µmol m"^-2~"s"^-1~") Observed"),
       y = expression(CH[4]~"flux (µmol m"^-2~"s"^-1~") Modeled"),
      # title = "Methane 2015-2023",
       color = "Year",
       fill = "Year")+
  annotate("text", 
        x = Inf, y = -Inf, hjust = 1.1, vjust = -0.5,
        label = paste0("Slope = ", round(Slope3, 2),
                          "\nR² = ", round(R2_3, 2)))


# Fit regressions for each year/ with hourly data
#merged_full2$Year_Plant<-as.factor(merged_full2$Year_Plant)

# Fit regressions per year
reg_stats_ch4 <- merged_full %>%
  group_by(Year_Plant) %>%
  group_modify(~ {
    data_sub <- .x %>% filter(!is.na(CH4_FLUX), !is.na(AMF_FCH4))
    if (nrow(data_sub) > 1) {
      ch4model_H <- lm(AMF_FCH4 ~ CH4_FLUX, data = data_sub)
      tibble(
        slope = coef(ch4model_H)[[2]],
        r2    = summary(ch4model_H)$r.squared)} 
    else {tibble(slope = NA_real_, r2 = NA_real_)}})

# Place labels near top-right of each facet/group
label_data_ch4 <- merged_full %>%
  group_by(Year_Plant) %>%
  summarise(
    x = max(CH4_FLUX, na.rm = TRUE),
    y = max(AMF_FCH4, na.rm = TRUE)) %>%
  left_join(reg_stats_ch4, by = "Year_Plant") %>%
  mutate(
    label = paste0("Slope = ", round(slope, 2), ", R² = ", round(r2, 2)),
   x = 0.05, 
   y = seq( from = 1.5, by = 0.2, 
            length.out = n()))

# Plot, slope/R2 separated by YEAR
ggplot(merged_full, aes(x = CH4_FLUX, y = AMF_FCH4, colour = as.factor(Year_Plant))) +
  geom_point(alpha = 0.6) +
  geom_smooth(method = "lm", se = FALSE, aes(color = as.factor(Year_Plant))) +
  geom_text(
    data = label_data_ch4,
    aes(x = x, y = y, label = label, colour = as.factor(Year_Plant)),
    hjust = 0, vjust = 0, show.legend = FALSE
  ) +
  theme_bw() +
  labs(
    x = expression(CH[4]~"flux (µmol m"^-2~"s"^-1~") Modeled"),
    y = expression(CH[4]~"flux (µmol m"^-2~"s"^-1~") Observed"),
    title = "Methane in Main Wetland (Hourly)",
    color = "Year"
  ) +
  theme(plot.title = element_text(hjust = 0.5))


#2016-2023

ch4mod_2020 <- lm(CH4_FLUX~AMF_FCH4, data = merged_2020)
summary(ch4mod_2020)
# Extract slope and R2
#coef(co2mod_2020)
#co2slope20 <- coef(co2mod_2020)[2]
#co2intercept20 <- coef(co2mod_2020)[1] # not used
#co2r2_20 <- summary(co2mod_2020)$r.squared
obs4<-merged_2020$AMF_FCH4
mod4 <-merged_2020$CH4_FLUX
valid4 <- complete.cases(obs4, mod4)
obs4 <- obs4[valid4]
mod4 <- mod4[valid4]
# Compute metrics
RMSE4  <- sqrt(mean((mod4 - obs4)^2))
Bias4 <- mean(mod4 - obs4)
Slope4 <- coef(lm(mod4 ~ obs4))[2]
R2_4 <- summary(lm(mod4 ~ obs4))$r.squared

# Print
cat("RMSE =", round(RMSE4, 3), "\n")
cat("Bias =", round(Bias4, 3), "\n")
cat("Slope =", round(Slope4, 3), "\n")
cat("R² =", round(R2_4, 3), "\n")

MODEL4<-ggplot(merged_2020, aes(x = AMF_FCH4, y = CH4_FLUX, colour = Year_NonPlant)) + 
  geom_point() +
  xlim(0, 1.5) +
  ylim(0, 1) +
  geom_smooth(method = "lm", se = FALSE, color = "black") +
  geom_abline(slope = 1, intercept = 0, color = "red", linetype = "dashed",size=0.8) +
  theme_bw() +
  theme(text = element_text(family = "serif"),
    axis.text.x = element_text(hjust = 1),
    plot.title = element_text(hjust = 0.5)) +
  labs(
    x = expression(CH[4]~"flux (µmol m"^-2~"s"^-1~") Observed"),
    y = expression(CH[4]~"flux (µmol m"^-2~"s"^-1~") Modeled"),
   # title = "Methane 2020-2023",
    color = "Year",
    fill = "Year") +
  annotate(
    "text",
    x = Inf, y = -Inf, hjust = 1.1, vjust = -0.5,
    label = paste0("Slope = ", round(Slope4, 2),
                   "\nR² = ", round(R2_4, 2)))

```
#Model~Obs
```{r}
CO2_model<-ggplot() +
  geom_point(
    data = merged_full,
    aes(x = AMF_FC, y = ECO_CO2_FLUX),
    color = "gray70",
    alpha = 0.7) +
  geom_point(
    data = merged_2020,
    aes(x = AMF_FC, y = ECO_CO2_FLUX),
    color = "black",
    alpha = 0.9) +
  geom_smooth(
    data = merged_2020,
    aes(x = AMF_FC, y = ECO_CO2_FLUX),
    method = "lm",
    se = FALSE,
    color = "gray20",
    size = 1) +
    geom_smooth(
    data = merged_full,
    aes(x = AMF_FC, y = ECO_CO2_FLUX),
    method = "lm",
    se = FALSE,
    color = "gray70",
    size = 1) +
  geom_abline(
    slope = 1,
    intercept = 0,
    color = "red",
    linetype = "dashed",
    size = 1) +
  xlim(-20, 20) + 
  ylim(-20, 20) +
  theme_bw() +
theme(text = element_text(family = "serif",size=12),
    axis.text.x = element_text(hjust = 1),
    plot.title = element_text(hjust = 0.5)) +
  labs(
    x = expression(CO[2]~"flux (µmol m"^-2~"s"^-1~") Observed"),
    y = expression(CO[2]~"flux (µmol m"^-2~"s"^-1~") Modeled")) +
  annotate(
    "text",
    x = Inf, y = -10,   # adjust placement if needed
    hjust = 1.1, vjust = 1,
    color = "gray30",
    label = paste0(
      #"2015–2023:\n",
      "Slope = ", round(Slope, 2), "\n",
      "R² = ", round(R2, 2), "\n"))+
      #"RMSE = ", round(RMSE3, 2), "\n",
     # "Bias = ", round(Bias3, 2))) +
  annotate(
    "text",
    x = Inf, y = -Inf,
    hjust = 1.1, vjust = -0.5,
    color = "black",
    label = paste0(
      #"2020–2023:\n",
      "Slope = ", round(Slope2, 2), "\n",
      "R² = ", round(R2_2020, 2), "\n"))
     # "RMSE = ", round(RMSE34, 2), "\n",
      #"Bias = ", round(Bias4, 2)))

Meth_model<-ggplot() +
  geom_point(
    data = merged_full,
    aes(x = AMF_FCH4, y = CH4_FLUX),
    color = "gray70",
    alpha = 0.7) +
  geom_point(
    data = merged_2020,
    aes(x = AMF_FCH4, y = CH4_FLUX),
    color = "black",
    alpha = 0.7) +
  geom_smooth(
    data = merged_2020,
    aes(x = AMF_FCH4, y = CH4_FLUX),
    method = "lm",
    se = FALSE,
    color = "gray20",
    size = 1) +
   geom_smooth(
    data = merged_full,
    aes(x = AMF_FCH4, y = CH4_FLUX),
    method = "lm",
    se = FALSE,
    color = "gray70",
    size = 1) +
  geom_abline(
    slope = 1,
    intercept = 0,
    color = "red",
    linetype = "dashed",
    size = 1) +
  xlim(0, 1.5) + 
  ylim(0, 1) +
  theme_bw() +
theme(text = element_text(family = "serif", size=12),
    axis.text.x = element_text(hjust = 1),
    plot.title = element_text(hjust = 0.5)) +
  labs(
    x = expression(CH[4]~"flux (µmol m"^-2~"s"^-1~") Observed"),
    y = expression(CH[4]~"flux (µmol m"^-2~"s"^-1~") Modeled")) +
  annotate(
    "text",
    x = Inf, y = 0.25,   # adjust placement if needed
    hjust = 1.1, vjust = 1,
    color = "gray30",
    label = paste0(
      #"2015–2023:\n",
      "Slope = ", round(Slope3, 2), "\n",
      "R² = ", round(R2_3, 2), "\n"))+
      #"RMSE = ", round(RMSE3, 2), "\n",
     # "Bias = ", round(Bias3, 2))) +
  annotate(
    "text",
    x = Inf, y = -Inf,
    hjust = 1.1, vjust = -0.5,
    color = "black",
    label = paste0(
      #"2020–2023:\n",
      "Slope = ", round(Slope4, 2), "\n",
      "R² = ", round(R2_4, 2), "\n"))
     # "RMSE = ", round(RMSE34, 2), "\n",
      #"Bias = ", round(Bias4, 2)))
```
##Figure 5
```{r}
Figure5<-ggarrange(CO2_model,Meth_model, align="hv", ncol=2, common.legend = TRUE, labels="AUTO")

ggsave(
  "Figure5.tiff",
  plot = Figure5,
  width = 3200,
  height = 2000,
  units = "px",
  dpi = 300,
  compression = "lzw")

```
#weather plots
```{r}
w2015<-read.csv("Nowc_w2015.csv", header = TRUE)
w2015<- w2015 [-c(1:3),-c(10:12)]
w2016<-read.csv("2016_w.csv", header = TRUE)
w2016<- w2016 [-c(1:3),-c(10:12)]
w2017<-read.csv("2017_w.csv", header = TRUE)
w2017<- w2017 [-c(1:3),-c(10:14)]
w2018<-read.csv("2018_w.csv", header = TRUE)
w2018<- w2018  [-c(1:3),-c(10:13)]
w2019<-read.csv("2019_w.csv", header = TRUE)
w2019<- w2019  [-c(1:3),-c(10:12)]
w2020<-read.csv("2020_w.csv", header = TRUE)
w2020<- w2020  [-c(1:3),-c(10:12)]
w2021<-read.csv("2021_w.csv", header = TRUE)
w2021<- w2021  [-c(1:3),-c(10:12)]
w2022<-read.csv("2022_w.csv", header = TRUE)
w2022<- w2022  [-c(1:3),-c(10:12)]
w2023<-read.csv("2023_w.csv", header = TRUE)
w2023<- w2023  [-c(1:3),-c(10:12)]

weather <- rbind(w2016,w2017,w2018,w2019,w2020,w2021,w2022,w2023)
#level2015 <-read.csv("level_2015.csv", header = TRUE, sep = ",")
level2016 <-read.csv("level_2016.csv", header = TRUE, sep= ",")
level2017 <-read.csv("level_2017.csv", header = TRUE, sep = ",")
level2018 <-read.csv("level_2018.csv", header = TRUE, sep = ",")
level2019 <-read.csv("level_2019.csv", header = TRUE, sep = ",")
level2020 <-read.csv("level_2020.csv", header = TRUE, sep = ",")
level2021 <-read.csv("level_2021.csv", header = TRUE, sep = ",")
level2022 <-read.csv("level_2022.csv", header = TRUE, sep = ",")
level2023 <-read.csv("level_2023.csv", header = TRUE, sep = ",")

names(level2016)[1] <- "Year"
names(level2016)[2] <- "DOY"
names(level2016)[3] <- "Level"
names(level2017)[1] <- "Year"
names(level2017)[2] <- "DOY"
names(level2017)[3] <- "Level"
names(level2018)[1] <- "Year"
names(level2018)[2] <- "DOY"
names(level2018)[3] <- "Level"
names(level2019)[1] <- "Year"
names(level2019)[2] <- "DOY"
names(level2019)[3] <- "Level"
names(level2020)[1] <- "Year"
names(level2020)[2] <- "DOY"
names(level2020)[3] <- "Level"
names(level2021)[1] <- "Year"
names(level2021)[2] <- "DOY"
names(level2021)[3] <- "Level"
names(level2022)[1] <- "Year"
names(level2022)[2] <- "DOY"
names(level2022)[3] <- "Level"
names(level2023)[1] <- "Year"
names(level2023)[2] <- "DOY"
names(level2023)[3] <- "Level"

water <- rbind(level2016,level2017,level2018,level2019,level2020,level2021,level2022,level2023)

# Add custom x-axis with one tick per year
years <- 2016:2024
ticks <- seq(1, by = 8760, length.out = length(years))
axis(1, at = ticks, labels = years)

par(mfrow=c(3,2)) # number of plots
par(mar = c(2,6,1,1)) #inner plot padding
par(oma = c(4,0,2,0))
par(family = "Times New Roman")


plot(weather$X.3, ylim= c(-20,40), type= "l", xaxt = "n", ylab = "Temperature (°C)", xlab="",
   #  cex.main=2, #change font size of title
   #  cex.sub=2, #change font size of subtitle
     cex.lab=1.5, #change font size of axis labels
     cex.axis=1.5) #change font size of axis text  ))
ticks <- seq(1, by = 8760, length.out = length(years))
axis(1, at = ticks, labels = FALSE, cex.axis = 2)
mtext("A", side = 3, adj = -0.1, line = 0.5, cex = 1.3, font=2)

plot(weather$X.4, ylim= c(0,110),type= "l", xaxt = "n", ylab="RH (%)", xlab="", cex.lab=1.5, cex.axis=1.5) 
ticks <- seq(1, by = 8760, length.out = length(years))
axis(1, at = ticks, labels = FALSE, cex.axis = 2)
mtext("B", side = 3, adj = -0.1, line = 0.5, cex = 1.3, font=2)

plot(weather$X.5,type= "l", xaxt = "n", xlab="",
    ylab = expression(Wind~(m~s^{-1})), cex.lab=1.5, cex.axis=1.5) 
ticks <- seq(1, by = 8760, length.out = length(years))
axis(1, at = ticks, labels = FALSE, cex.axis = 2)
mtext("C", side = 3, adj = -0.1, line = 0.5, cex = 1.3, font=2)

plot(weather$X.6,  ylim= c(0,50),type= "l", xaxt = "n", ylab="Rainfall (mm)", xlab="", cex.lab=1.5, cex.axis=1.5) 
ticks <- seq(1, by = 8760, length.out = length(years))
axis(1, at = ticks, labels = FALSE, cex.axis = 2)
mtext("D", side = 3, adj = -0.1, line = 0.5, cex = 1.3, font=2)

plot(weather$X.7, type= "l", xaxt = "n", xlab="",
     ylab = expression(Radiation~(Watts~m^{-2})),cex.lab=1.5, cex.axis=1.5) 
ticks <- seq(1, by = 8760, length.out = length(years))
axis(1, at = ticks, labels = years, cex.axis = 1.5)
mtext("E", side = 3, adj = -0.1, line = 0.5, cex = 1.3, font=2)

plot(water$Level, type= "l", xaxt = "n", ylab = "Water Level (m)", xlab="", cex.lab=1.5, cex.axis=1.5) 
ticks <- seq(1, by = 8760, length.out = length(years))
axis(1, at = ticks, labels = years, cex.axis = 1.5)
mtext("F", side = 3, adj = -0.1, line = 0.5, cex = 1.3, font=2)
```

#____________
#old
##Read in plant cells
```{r}
Crash here!
#these files are directly output from ecosys
#02 (row 2), 01 (column 2), 0 (soil), YYYY, hourly, carbon
hc2015<-read.delim("020102015hc", header = TRUE, sep = "", dec = ".")
hc2016<-read.delim("020102016hc", header = TRUE, sep = "", dec = ".")
hc2017<-read.delim("020102017hc", header = TRUE, sep = "", dec = ".")
hc2018<-read.delim("020102018hc", header = TRUE, sep = "", dec = ".")
hc2019<-read.delim("020102019hc", header = TRUE, sep = "", dec = ".")
hc2020<-read.delim("020102020hc", header = TRUE, sep = "", dec = ".")
hc2021<-read.delim("020102021hc", header = TRUE, sep = "", dec = ".")
hc2022<-read.delim("020102022hc", header = TRUE, sep = "", dec = ".")
hc2023<-read.delim("020102023hc", header = TRUE, sep = "", dec = ".")

plot(hc2023$CH4_FLUX)

full<-rbind(hc2015,hc2016,hc2017,hc2018,hc2019,hc2020,hc2021,hc2022, hc2023)

str(full)
full$DATE <- lubridate::dmy(full$DATE)

full_july<- full %>%
  filter(lubridate::month(DATE) == 7)

#write.csv(full_july, "C:/Erin/ecosys/Channel/full_julyplants.csv")
#write.csv(full, "C:/Erin/ecosys/Channel/full_channel_plants.csv")

```
##Read in OPEN Cells
```{r}
#these files are directly output from ecosys
#03 (row 3), 01 (column 2), 0 (soil), YYYY, hourly, carbon
hc2015b<-read.delim("030102015hc", header = TRUE, sep = "", dec = ".")
hc2016b<-read.delim("030102016hc", header = TRUE, sep = "", dec = ".")
hc2017b<-read.delim("030102017hc", header = TRUE, sep = "", dec = ".")
hc2018b<-read.delim("030102018hc", header = TRUE, sep = "", dec = ".")
hc2019b<-read.delim("030102019hc", header = TRUE, sep = "", dec = ".")
hc2020b<-read.delim("030102020hc", header = TRUE, sep = "", dec = ".")
hc2021b<-read.delim("030102021hc", header = TRUE, sep = "", dec = ".")
hc2022b<-read.delim("030102022hc", header = TRUE, sep = "", dec = ".")
hc2023b<-read.delim("030102023hc", header = TRUE, sep = "", dec = ".")


fullb<-rbind(hc2015b,hc2016b,hc2017b,hc2018b,hc2019b,hc2020b,hc2021b,hc2022b, hc2023b)

str(fullb)

fullb$DATE <- lubridate::dmy(fullb$DATE)

fullb_july<- fullb %>%
  filter(lubridate::month(DATE) == 7)

#write.csv(fullb_july, "C:/Erin/ecosys/Channel/full_julyopen.csv")
#write.csv(fullb, "C:/Erin/ecosys/Channel/full_channel_open.csv")

```

```{r}
#this is to compare AMF tower to ecosys. The file Both_ecosys_2023.csv takes the outputs from the previous chunks (hourly plants and open 2015-2023) and puts the data alongside AMF. The columns are manually copied over from those files to the both_ecosys_2023.csv file.

both <- merged_full

#str(both)  
#both$DATE <- lubridate::mdy(both$DATE)

both_Jan<- both %>%
  filter(lubridate::month(DATE) == 1) %>%
  group_by(HOUR) %>% 
  summarise(AMF_CO2 = mean(AMF_FC, na.rm = T), AMF_FCH4 = mean(AMF_FCH4, na.rm = T), CO2 = mean(ECO_CO2_FLUX, na.rm = T), CH4 = mean(CH4_FLUX, na.rm = T ))

both_Feb<- both %>%
  filter(lubridate::month(DATE) == 2)%>%
 group_by(HOUR) %>% 
  summarise(AMF_CO2 = mean(AMF_FC, na.rm = T), AMF_FCH4 = mean(AMF_FCH4, na.rm = T), CO2 = mean(ECO_CO2_FLUX, na.rm = T), CH4 = mean(CH4_FLUX, na.rm = T ))

both_Mar<- both %>%
  filter(lubridate::month(DATE) == 3) %>%
 group_by(HOUR) %>% 
  summarise(AMF_CO2 = mean(AMF_FC, na.rm = T), AMF_FCH4 = mean(AMF_FCH4, na.rm = T), CO2 = mean(ECO_CO2_FLUX, na.rm = T), CH4 = mean(CH4_FLUX, na.rm = T ))

both_Apr<- both %>%
  filter(lubridate::month(DATE) == 4) %>%
 group_by(HOUR) %>% 
  summarise(AMF_CO2 = mean(AMF_FC, na.rm = T), AMF_FCH4 = mean(AMF_FCH4, na.rm = T), CO2 = mean(ECO_CO2_FLUX, na.rm = T), CH4 = mean(CH4_FLUX, na.rm = T ))

both_May<- both %>%
  filter(lubridate::month(DATE) == 5) %>%
 group_by(HOUR) %>% 
  summarise(AMF_CO2 = mean(AMF_FC, na.rm = T), AMF_FCH4 = mean(AMF_FCH4, na.rm = T), CO2 = mean(ECO_CO2_FLUX, na.rm = T), CH4 = mean(CH4_FLUX, na.rm = T ))

both_June<- both %>%
  filter(lubridate::month(DATE) == 6) %>%
 group_by(HOUR) %>% 
  summarise(AMF_CO2 = mean(AMF_FC, na.rm = T), AMF_FCH4 = mean(AMF_FCH4, na.rm = T), CO2 = mean(ECO_CO2_FLUX, na.rm = T), CH4 = mean(CH4_FLUX, na.rm = T ))

both_July<- both %>%
  filter(lubridate::month(DATE) == 7) 

both_July2<-both_July %>%
  group_by(HOUR) %>% 
  summarise(AMF_CO2 = mean(AMF_FC, na.rm = T), AMF_FCH4 = mean(AMF_FCH4, na.rm = T), ecosys_CO2 = mean(ECO_CO2_FLUX, na.rm = T), ecosys_CH4 = mean(CH4_FLUX, na.rm = T ))

both_Aug<- both %>%
  filter(lubridate::month(DATE) == 8)

both_Aug2<- both_Aug%>%
 group_by(HOUR) %>% 
  summarise(AMF_CO2 = mean(AMF_FC, na.rm = T), AMF_FCH4 = mean(AMF_FCH4, na.rm = T), ecosys_CO2 = mean(ECO_CO2_FLUX, na.rm = T), ecosys_CH4 = mean(CH4_FLUX, na.rm = T ))

both_Sep<- both %>%
  filter(lubridate::month(DATE) == 9)

both_Sep2<- both_Sep%>%
 group_by(HOUR) %>% 
  summarise(AMF_CO2 = mean(AMF_FC, na.rm = T), AMF_FCH4 = mean(AMF_FCH4, na.rm = T), ecosys_CO2 = mean(ECO_CO2_FLUX, na.rm = T), ecosys_CH4 = mean(CH4_FLUX, na.rm = T ))

both_Oct<- both %>%
  filter(lubridate::month(DATE) == 10) 

both_Oct2<- both_Oct%>%
 group_by(HOUR) %>% 
  summarise(AMF_CO2 = mean(AMF_FC, na.rm = T), AMF_FCH4 = mean(AMF_FCH4, na.rm = T), ecosys_CO2 = mean(ECO_CO2_FLUX, na.rm = T), ecosys_CH4 = mean(CH4_FLUX, na.rm = T ))

both_Nov<- both %>%
  filter(lubridate::month(DATE) == 11) %>%
 group_by(HOUR) %>% 
  summarise(AMF_CO2 = mean(AMF_FC, na.rm = T), AMF_FCH4 = mean(AMF_FCH4, na.rm = T), CO2 = mean(ECO_CO2_FLUX, na.rm = T), CH4 = mean(CH4_FLUX, na.rm = T ))

both_Dec<- both %>%
  filter(lubridate::month(DATE) == 12) %>%
 group_by(HOUR) %>% 
  summarise(AMF_CO2 = mean(AMF_FC, na.rm = T), AMF_FCH4 = mean(AMF_FCH4, na.rm = T), CO2 = mean(ECO_CO2_FLUX, na.rm = T), CH4 = mean(CH4_FLUX, na.rm = T ))

winter <-rbind(both_Nov, both_Dec, both_Jan, both_Feb )

spring <-rbind(both_Mar,both_Apr, both_May, both_June)

summer<- rbind(both_July2, both_Aug2, both_Sep2, both_Oct2)


```
##Base R plots (working)
```{r}
#Co2 plots comparing ecosys to Ameriflux
months <- c("July", "August", "September","October")
month_positions <- c(0, 25, 50, 75)
tick_positions <- rep(c(6, 12, 18, 24), times = 4) + rep(seq(0, 75, by = 25), each = 4)

plot(summer$AMF_CO2)

par(mar = c(5, 4, 4, 2) + 0.5)
plot(summer$AMF_CO2, pch=16, xlab="", ylab= expression("CO"[2] ~"Flux"~ "(umol m"^2 ~"s"^-1~")"), 
     xaxt="n",oma=c(2, 3, 5, 2),
   type="b",col="red",ylim=c(-10,6))
   title(main= expression("Main Channel CO"[2] ~"fluxes", line = 2, cex.main = 1.7))
   mtext("24 Hour Cycle, Averaged from 2015-2023", side = 3, line = 0.5, cex = 1.2)

axis(1, at = tick_positions, labels = rep(c(6, 12, 18, 24), times = 4))
mtext(months, side = 1, at = c(12, 37, 62, 87), line = 3, font = 2, cex = 1.2)

#axis(1, at = seq(0, 24, 6), labels = seq(0, 24, 6))
points(summer$ecosys_CO2, pch=16, xlab="", ylab="CO2 Flux", 
   type="b",col="black")

legend("topright",legend=c("Field data (Ameriflux)",
                           "Model data (ecosys)"),
  text.col=c("red","black"), pch=c(16),col=c("red","black"))

abline(v = c(25, 50, 75), col = "gray", lty = "dashed")





```

```{r}
#methane plots comparing ecosys to Ameriflux

months <- c("July", "August", "September","October")
month_positions <- c(0, 25, 50, 75)
tick_positions <- rep(c(6, 12, 18, 24), times = 4) + rep(seq(0, 75, by = 25), each = 4)


#par(mar = c(5, 4, 4, 2) + 0.5)
plot(summer$AMF_FCH4, pch=16, xlab="", 
     ylab= expression("CH"[4] ~"Flux"~ "(umol m"^2 ~"s"^-1~")"), 
     xaxt="n",oma=c(2, 3, 5, 2),
   type="b",col="red", ylim=c(0,1))

   title(main= expression("Main Channel CH"[4] ~"fluxes", 
                          line = 2, cex.main = 1.7))
   mtext("24 Hour Cycle, Averaged from 2015-2023", side = 3, 
         line = 0.5, cex = 1.2)

axis(1, at = tick_positions, labels = rep(c(6, 12, 18, 24),
                                          times = 4))
mtext(months, side = 1, at = c(12, 37, 62, 87), 
      line = 3, font = 2, cex = 1.2)

#axis(1, at = seq(0, 24, 6), labels = seq(0, 24, 6))
points(summer$ecosys_CH4, pch=16, xlab="", ylab="CH4 Flux", 
   type="b",col="black")

legend("topright",legend=c("Field data (Ameriflux)","Model data (ecosys)"),
  text.col=c("red","black"), pch=c(16),col=c("red","black"))

abline(v = c(25, 50, 75), col = "gray", lty = "dashed")
```
#daily co2
```{r}
#OPTION 2
# Fit regression model, Daily averaged not hourly
co2model <- lm(AMF_CO2 ~ CO2_FLUX, data = dfCO2_clean)
# Extract slope and R2
co2slope <- coef(co2model)[2]
co2intercept <- coef(co2model)[1]
co2r2 <- summary(co2model)$r.squared

str(dfCO2_clean)

#1 Regression line
ggplot(dfCO2_clean, aes(x = CO2_FLUX, y=AMF_CO2, colour = Year_Plant)) +
  geom_point() +
   geom_smooth(method = "lm", se = FALSE, color = "black") +  # regression line
  theme_bw() +
  theme(axis.text.x = element_text(hjust = 1),
        plot.title = element_text(hjust=0.5))+
  labs(x = expression(CO[2]~"flux (µmol m"^-2~"s"^-1~") Modeled"),
       y = expression(CO[2]~"flux (µmol m"^-2~"s"^-1~") Observed"),
       title = "Carbon Dioxide in Main Wetland (Daily)",
       color = "Year",
       fill = "Year")+
  annotate("text", 
          x = Inf, y = -Inf, hjust = 1.1, vjust = -0.5,
        label = paste0("Slope = ", round(co2slope, 2),
                          "\nR² = ", round(co2r2, 2)))
library(broom)



dfCO2_clean$Year_Plant<-as.factor(dfCO2_clean$Year_Plant)
# Fit regressions for each year
reg_stats <- dfCO2_clean %>%
  group_by(Year_Plant) %>%
  group_modify(~ {
    co2model2 <- lm(AMF_CO2 ~ CO2_FLUX, data = .x)
    tibble(
      slope = coef(co2model2)[[2]],
      r2    = summary(co2model2)$r.squared)})

# Place labels near top-right of each facet/group
label_data <- dfCO2_clean %>%
  group_by(Year_Plant) %>%
  summarise(
    x = max(CO2_FLUX, na.rm = TRUE),
    y = min(AMF_CO2, na.rm = TRUE)
  ) %>%
  left_join(reg_stats, by = "Year_Plant") %>%
  mutate(
    label = paste0("Slope = ", round(slope, 2), ", R² = ", round(r2, 2)),
    x = 5, y = seq( from = -8, by = 0.5, 
                    length.out = n()))

# Plot, slope/R2 separated by YEAR
ggplot(dfCO2_clean, aes(x = CO2_FLUX, y = AMF_CO2, colour = as.factor(Year_Plant))) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE, aes(color = as.factor(Year_Plant))) +
  geom_text(
    data = label_data,
    aes(x = x, y = y, label = label, colour = as.factor(Year_Plant)),
    hjust = 1, vjust = 1, show.legend = FALSE
  ) +
  theme_bw() +
  labs(
    x = expression(CO[2]~"flux (µmol m"^-2~"s"^-1~") Modeled"),
    y = expression(CO[2]~"flux (µmol m"^-2~"s"^-1~") Observed"),
    title = "Carbon Dioxide in Main Wetland (Daily)",
    color = "Year"
  ) +
  theme(plot.title = element_text(hjust = 0.5))
```
#daily metthane
```{r}





# Average by DAY
dfCH4_clean <- merged_full %>%
  mutate(
    Day = yday(DATE)) %>%
  group_by(Year_Plant, Day) %>%
  filter(!is.na(Year_Plant)) %>%
  summarise(
    CH4_FLUX = mean(CH4_FLUX, na.rm = TRUE),
    AMF_CH4  = mean(AMF_FCH4,  na.rm = TRUE),
    Date_day = first(as.Date(DATE))) %>%
  ungroup()


#DAILY Regression
# Fit regression model
ch4model <- lm(AMF_CH4 ~ CH4_FLUX, data = dfCH4_clean)

# Extract slope and R2
ch4slope <- coef(ch4model)[2]
ch4intercept <- coef(ch4model)[1]
ch4r2 <- summary(ch4model)$r.squared

ggplot(dfCH4_clean, aes(x = CH4_FLUX, y=AMF_CH4, colour = Year_Plant)) +
  geom_point() +
   geom_smooth(method = "lm", se = FALSE, color = "black")+
  theme_bw() +
  theme(axis.text.x = element_text(hjust = 1))+
  labs(x = expression(CH[4]~"flux (µmol m"^-2~"s"^-1~") Modeled"),
       y = expression(CH[4]~"flux (µmol m"^-2~"s"^-1~") Observed"),
       title = "Methane in Main Wetland",
       color = "Year",
       fill = "Year")+
  annotate("text", 
           x = Inf, y = -Inf, hjust = 1.1, vjust = -0.5,
           label = paste0("Slope = ", round(ch4slope, 2),
                          "\nR² = ", round(ch4r2, 2)))

#dfCH4_clean$Year_Plant<-as.factor(dfCH4_clean$Year_Plant)
# Fit regressions for each year
reg_stats2 <- dfCH4_clean %>%
  group_by(Year_Plant) %>%
  group_modify(~ {
    ch4model2 <- lm(AMF_CH4 ~ CH4_FLUX, data = .x)
    tibble(
      slope = coef(ch4model2)[["CH4_FLUX"]],
      r2    = summary(ch4model2)$r.squared
    )
  })

label_data2 <- dfCH4_clean %>%
  group_by(Year_Plant) %>%
  summarise(x = max(CH4_FLUX, na.rm = TRUE),
            y = max(AMF_CH4, na.rm = TRUE)) %>%
  left_join(reg_stats2, by = "Year_Plant") %>%
  mutate(label = paste0("Slope = ", round(slope, 2), 
                   ", R² = ", round(r2, 2)),
    x = 0.2, y = seq(      
      from = 1, 
      by = 0.07, 
      length.out = n()))

# Plot
ggplot(dfCH4_clean, aes(x = CH4_FLUX, y = AMF_CH4, colour = as.factor(Year_Plant))) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE, aes(color = as.factor(Year_Plant))) +
  geom_text(
    data = label_data2,
    aes(x = x, y = y, label = label, colour = as.factor(Year_Plant)),
    hjust = 1, vjust = 1, show.legend = FALSE) +
  theme_bw() +
  theme(plot.title = element_text(hjust=0.5))+
  labs(
    x = expression(CH[4]~"flux (µmol m"^-2~"s"^-1~") Modeled"),
    y = expression(CH[4]~"flux (µmol m"^-2~"s"^-1~") Observed"),
    title = "Methane in Main Wetland",
    color = "Year"
  )


```
##more plots (with error bars)
```{r}
both_July3<-both_July %>%
  group_by(HOUR) %>% 
  summarise(n = n(),
            AMF_CO2 = mean(AMF_FC, na.rm = T), 
            AMF_CO2_sd = sd(AMF_FC, na.rm = T), 
            AMF_CO2_se =AMF_CO2_sd/ sqrt(n),
            AMF_CH4 = mean(AMF_FCH4, na.rm = T), 
            AMF_CH4_sd = sd(AMF_FCH4, na.rm = T), 
            AMF_CH4_se =AMF_CH4_sd/ sqrt(n),
            
            ecosys_CO2 = mean(CO2_avg, na.rm = T), 
            CO2_avg_sd = sd(CO2_avg, na.rm = T),
            CO2_avg_se =CO2_avg_sd/ sqrt(n),
            ecosys_CH4 = mean(CH4_avg, na.rm = T), 
            CH4_avg_sd =sd(CH4_avg, na.rm = T),
            CH4_avg_se =CH4_avg_sd/ sqrt(n))
#CO2 plot
  ggplot(both_July3,aes(HOUR, ecosys_CO2)) +
  geom_point() +
    geom_jitter()+
  geom_errorbar(
    aes(ymin = ecosys_CO2 - CO2_avg_se, ymax = ecosys_CO2 + CO2_avg_se)) +
    geom_point() +
    geom_errorbar(
    aes(ymin = AMF_CO2 - AMF_CO2_se, ymax = AMF_CO2 + AMF_CO2_se, color="red")) +
    ggtitle("Carbon Dioxide in Ecosys and AMF") +
    xlab("24 hr Average (2015-2023)") + 
    ylab(expression(CO[2]~(mu~mol~m^-2~s^-1)))+
    theme_bw()+
    theme(
      plot.title = element_text(size=14, face="bold.italic", hjust=0.5),
      axis.title.x = element_text(size=14, face="bold"),
      axis.text.x = element_text(size=14),
      axis.text.y = element_text(size=14),
      axis.title.y = element_text(size=14, face="bold"),
      legend.text = element_blank())+
   # annotate("text", x = 3.5, y = 7, label = "Custom Legend", size = 5, fontface = "bold") +
    geom_point(aes(x = 22.5, y = -7.5), color = "red", size = 4) +
    annotate("text",x = 23, y = -7.5, label = "AMF", hjust = 0) +
    geom_point(aes(x = 22.5, y = -8), color = "black", size = 4) +
    annotate("text",x = 23, y = -8, label = "ecosys", hjust = 0)
     

#methane plot
  ggplot(both_July3,aes(HOUR, ecosys_CH4)) +
  geom_point() +
  geom_errorbar(
    aes(ymin = ecosys_CH4 - CH4_avg_se, ymax = ecosys_CH4 + CH4_avg_se)) +
    geom_point() +
    geom_errorbar(
    aes(ymin = AMF_CH4 - AMF_CH4_se, ymax = AMF_CH4 + AMF_CH4_se, color="red")) +
    ggtitle("Methane in Ecosys and AMF") +
    xlab("24 hr Average (2015-2023)") +  
    ylab(expression(CH[4]~(mu~mol~m^-2~s^-1)))+
    theme_bw()+
    theme(
      plot.title = element_text(size=14, face="bold.italic", hjust=0.5),
      axis.title.x = element_text(size=14, face="bold"),
      axis.text.x = element_text(size=14),
      axis.text.y = element_text(size=14),
      axis.title.y = element_text(size=14, face="bold"))+
        geom_point(aes(x = 22.5, y = 0.42), color = "red", size = 4) +
    annotate("text",x = 23, y = 0.42, label = "AMF", hjust = 0) +
    geom_point(aes(x = 22.5, y = 0.4), color = "black", size = 4) +
    annotate("text",x = 23, y = 0.4, label = "ecosys", hjust = 0)
```
##Model fitting
```{r}
library(Metrics)
bth_clean <- na.omit(both)
rmse(bth_clean$AMF_FC, bth_clean$CO2_avg)
rmse(bth_clean$AMF_FCH4, bth_clean$CH4_avg)

#if you want specific rmse by month, those are here. 
##Remove NAs
July_clean <- na.omit(both_July)
plot(both_July$CO2_avg)
plot(both_July$CH4_avg)
plot(both_July$AMF_FC)
plot(both_July$AMF_FCH4)
#July_outliers <- July_clean %>% filter(AMF_FC > -300) #remove outlier
rmse(both_July$AMF_FC, both_July$CO2_avg)
rmse(both_July$AMF_FCH4, both_July$CH4_avg)

Aug_clean <- na.omit(both_Aug)
plot(Aug_clean$CO2_avg)
plot(Aug_clean$CH4_avg)
plot(Aug_clean$AMF_FC)
plot(Aug_clean$AMF_FCH4)
rmse(Aug_clean$AMF_FC, Aug_clean$CO2_avg)
rmse(Aug_clean$AMF_FCH4, Aug_clean$CH4_avg)

Sep_clean <- na.omit(both_Sep)
plot(Sep_clean$CO2_avg)
plot(Sep_clean$CH4_avg)
plot(Sep_clean$AMF_FC)
plot(Sep_clean$AMF_FCH4)
rmse(Sep_clean$AMF_FC, Sep_clean$CO2_avg)
rmse(Sep_clean$AMF_FCH4, Sep_clean$CH4_avg)

Oct_clean <- na.omit(both_Oct)
plot(Oct_clean$CO2_avg)
plot(Oct_clean$CH4_avg)
plot(Oct_clean$AMF_FC)
plot(Oct_clean$AMF_FCH4)
rmse(Oct_clean$AMF_FC, Oct_clean$CO2_avg)
rmse(Oct_clean$AMF_FCH4, Oct_clean$CH4_avg)

July_outliers %>% 
 # filter(obs_CO2 > -300) %>% #removing one outlier
  mutate(DateTime = paste(DATE,HOUR,sep = ".")) %>% 
ggplot(.)+
  geom_jitter(aes(DateTime,AMF_FC, color = "Oberved"), alpha = 0.65)+
  geom_jitter(aes(DateTime,CO2_avg, color = "Modeled"), alpha = 0.65)+
  labs(title = "Carbon Dioxide Fluxes in July",
       subtitle = "2015-2023 July data",
       x = "24 Hour Average", y = "CO2 Flux (umol  m<sup>-2</sup> s<sup>-1</sup>)")+
  theme_bw()+
  theme(legend.title = element_blank())

July_outliers %>% 
 # filter(AMF_FC > -300) %>%
ggplot(.)+
  geom_smooth(aes(HOUR,AMF_FC, color = "Oberved"))+
  geom_smooth(aes(HOUR,CO2_avg, color = "Modeled"))+
  labs(title = "Carbon Dioxide Fluxes in July",
       subtitle = "2015-2023 July data",
       x = "24 Hour Average", y = "CO2 Flux (umol m-2 s-1)")+
  theme_bw()+
  theme(legend.title = element_blank())

```
##Channel comparison
##CH4 Vegetation
```{r}
make_plot_CH4 <- function(df, title_label) {
  ggplot(df, aes(x = as.numeric(HOUR))) +
    # Observations: mean ± SE ribbon and line
    stat_summary(aes(y = AMF_FCH4, color = "Observed", fill = "Observed"), 
                 fun = mean, geom = "line", size = 0.8) +
    stat_summary(aes(y = AMF_FCH4, fill = "Observed"), 
                 fun.data = mean_se, geom = "ribbon", 
                 alpha = 0.3, color = NA) +
    # Model: line only
    stat_summary(aes(y = CH4_FLUX, color = "Modeled"), 
                 fun = mean, geom = "line", size = 0.8) +
    facet_grid(~MonthYear_Plant, scales = "free_x", space = "free_x") +
   # scale_x_continuous(breaks = c(0, 12, 24)) +
   # scale_y_continuous(limits = c(-2, 10), expand = c(0,0)) +
    scale_color_manual(name = "Source", 
                       values = c("Observed" = "black", "Modeled" = "red")) +
    scale_fill_manual(name = "Source", 
                      values = c("Observed" = "grey30", "Modeled" = "red")) +
    labs(x = "Hour", 
         y = expression(CH[4]~flux~(mu*mol~m^{-2}~s^{-1})),
         title = title_label) +
    theme_bw() +
    theme(
      plot.title = element_text(hjust = 0.5, 
                                size = 14),   # center title
      strip.background = element_blank(),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      legend.position = "top",
      axis.title.x= element_blank(),
      axis.text.x = element_blank()
    )
}

p1_cH4 <- make_plot_CH4(merged_full, "Methane in the Channel")

```
##CH4 Non-Vegetation
```{r}
make_plot_Ch4b <- function(df, title_label) {
  ggplot(df, aes(x = as.numeric(HOUR))) +
    # Observations: mean ± SE ribbon and line
    stat_summary(aes(y = AMF_FCH4, color = "Observed", fill = "Observed"), 
                 fun = mean, geom = "line", size = 0.8) +
    stat_summary(aes(y = CH4_FLUX, fill = "Observed"), 
                 fun.data = mean_se, geom = "ribbon", alpha = 0.3, color = NA) +
    # Model: line only
    stat_summary(aes(y = CH4_FLUX, color = "Modeled"), 
                 fun = mean, geom = "line", size = 0.8) +
    facet_grid(~MonthYear_Plant, scales = "free_x", space = "free_x") +
    scale_x_continuous(breaks = c(0, 12, 24)) +
    #scale_y_continuous(limits = c(-2, 5), expand = c(0,0)) +
    scale_color_manual( 
                       values = c("Observed" = "black", "Modeled" = "red")) +
    scale_fill_manual(
                      values = c("Observed" = "grey30", "Modeled" = "red")) +
    labs(x = "Hour", 
         y = expression(CH[4]~flux~(mu*mol~m^{-2}~s^{-1})),
         title = title_label) +
    theme_bw() +
    theme(
      plot.title = element_text(hjust = 0.5, size = 14),   # center title
      strip.background = element_blank(),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      legend.position = "top"  # or "bottom", "right", etc.
    )
}

p2_ch4b <- make_plot_Ch4b(merged_full, " Methane in Cove | No Vegetation")

ggarrange(p1_cH4, p2_ch4b, nrow=2, common.legend = TRUE)
```
