---
title: "Ecosys Cove"
author: "Erin Hassett"
date: "11/4/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---
#load libraries
```{r setup, include=FALSE}

#This script is to plot the carbon fluxes from the Old Woman Creek Cove only (channel is in a different script)

getwd()
setwd("C:/Erin/ecosys/Cove")
library(ggplot2) #making plots
library(dplyr) #data manipulation/ cleaning
library(tidyr) #data manipulation/ cleaning
library(magrittr)
library(ggpubr)
library(lubridate) #working with Time
library(jsonlite)
library(readr) #read_csv
library(hydroGOF) #rmse
library(readxl) #read excel file
```
#bOA parameters
```{r}
trials_ch4 <- read.csv("trial_params_cove_ch4.csv")
trials_co2 <- read.csv("trial_params_cove_co2.csv")
last30<- tail(trials_ch4,30)
mean30 <- colMeans(last30)

p1a <- ggplot(trials_ch4, aes(x = seq_along(VMXC), y = VMXC)) +
  geom_line() + ggtitle("Hydrogenotrophic Methanogens") +
  ylab("Oxidation rate(g C g-1 C h-1)") + xlab("Trial")+
  theme(plot.title=element_text(hjust=0.5),
        axis.title.x=element_blank())

p2a <- ggplot(trials_ch4, aes(x = seq_along(VMX4), y = VMX4)) +
  geom_line() + ggtitle("Methanotrophs") +
  ylab("Oxidation rate(g C g-1 C h-1)") + xlab("Trial")+
  theme(plot.title=element_text(hjust=0.5),
        axis.title.y=element_blank(),
        axis.title.x=element_blank())

p3a <- ggplot(trials_ch4, aes(x = seq_along(VMXM), y = VMXM)) +
  geom_line() + ggtitle("Acetotrophic Methanogens") +
  ylab("Oxidation rate(g C g-1 C h-1)") + xlab("Trial")+
  theme(plot.title=element_text(hjust=0.5))

p4a <- ggplot(trials_ch4, aes(x = seq_along(VMXF), y = VMXF)) +
  geom_line() + ggtitle("Fungi") +
  ylab("Oxidation rate (g C g-1 C h-1)") + xlab("Trial")+
  theme(plot.title=element_text(hjust=0.5),
        axis.title.y=element_blank())

ggarrange(p1a,p2a,p3a,p4a, nrow=2, ncol=2)

#Channel CO2
p1 <- ggplot(trials_co2, aes(x = seq_along(rubcarb), y = rubcarb)) +
  geom_line() + ggtitle("Rubisco Carboxylation") +
  ylab("µmol g⁻¹ s⁻¹") + xlab("Trial")

p2 <- ggplot(trials_co2, aes(x = seq_along(rubox), y = rubox)) +
  geom_line() + ggtitle("Rubisco Oxygenation") +
  ylab("µmol g⁻¹ s⁻¹") + xlab("Trial")

p3 <- ggplot(trials_co2, aes(x = seq_along(shortalb), y = shortalb)) +
  geom_line() + ggtitle("Shortwave Albedo") +
  ylab("%") + xlab("Trial")

p4 <- ggplot(trials_co2, aes(x = seq_along(paralb), y = paralb)) +
  geom_line() + ggtitle("PAR Albedo") +
  ylab("%") + xlab("Trial")

p5 <- ggplot(trials_co2, aes(x = seq_along(rootpor), y = rootpor)) +
  geom_line() + ggtitle("Root Porosity") +
  ylab("m³/m³") + xlab("Trial")

p6 <- ggplot(trials_co2, aes(x = seq_along(leafon), y = leafon)) +
  geom_line() + ggtitle("Leaves On") +
  ylab("Hours in the Year") + xlab("Trial")

p7 <- ggplot(trials_co2, aes(x = seq_along(leaffoff), y = leaffoff)) +
  geom_line() + ggtitle("Leaf Off") +
  ylab("Hours in the Year") + xlab("Trial")

ggarrange(p1, p2, p3, p4, p5, p6, p7, nrow = 3, ncol = 3)



h1 <- ggplot(trials_ch4, aes( x = VMXC)) +
  geom_histogram() + ggtitle("Hydrogenotrophic Methanogens") +
  xlab("Oxidation rate(g C g⁻¹ C h⁻¹)") + ylab("Frequency")+
  theme_bw()+
  theme(plot.title=element_text(hjust=0.5),
        axis.title.x=element_blank())

h2 <- ggplot(trials_ch4, aes(x = (VMX4))) +
  geom_histogram() + ggtitle("Methanotrophs") +
  xlab("Oxidation rate(g C g⁻¹ C h⁻¹)") + ylab("Freequency")+
    theme_bw()+
  theme(plot.title=element_text(hjust=0.5),
        axis.title.y=element_blank(),
        axis.title.x=element_blank())

h3 <- ggplot(trials_ch4, aes(x = VMXM)) +
  geom_histogram() + ggtitle("Acetotrophic Methanogens") +
  xlab("Oxidation rate(g C g⁻¹ C h⁻¹)") + ylab("Freequency")+
    theme_bw()+
  theme(plot.title=element_text(hjust=0.5))

h4 <- ggplot(trials_ch4, aes(x = VMXF)) +
  geom_histogram() + ggtitle("Fungi") +
  xlab("Oxidation rate (g C g⁻¹ C h⁻¹)") + ylab("Frequency")+
    theme_bw()+
  theme(plot.title=element_text(hjust=0.5),
        axis.title.y=element_blank())

ggarrange(h1,h2,h3,h4, nrow=2, ncol=2)

#Channel CO2
h5 <- ggplot(trials_co2, aes(x = (rubcarb))) +
  geom_histogram() + ggtitle("Rubisco Carboxylation") +
  xlab("µmol g⁻¹ s⁻¹") + ylab("Frequency")+
    theme_bw()+
  theme(plot.title=element_text(hjust=0.5))
       # axis.title.y=element_blank())

h6 <- ggplot(trials_co2, aes(x = rubox)) +
  geom_histogram() + ggtitle("Rubisco Oxygenation") +
  xlab("µmol g⁻¹ s⁻¹") + ylab("frequency")+
  theme_bw()+
  theme(plot.title=element_text(hjust=0.5),
        axis.title.y=element_blank())

h7 <- ggplot(trials_co2, aes(x = shortalb)) +
  geom_histogram() + ggtitle("Shortwave Albedo") +
  xlab("%") + ylab("frequency")+
    theme_bw()+
  theme(plot.title=element_text(hjust=0.5),
        axis.title.y=element_blank())

h8 <- ggplot(trials_co2, aes(x = paralb)) +
  geom_histogram() + ggtitle("PAR Albedo") +
  xlab("%") + ylab("Frequency")+
    theme_bw()+
  theme(plot.title=element_text(hjust=0.5))
       # axis.title.y=element_blank())

h9 <- ggplot(trials_co2, aes(x = (rootpor))) +
  geom_histogram() + ggtitle("Root Porosity") +
  xlab("m³/m³") + ylab("Frequency")+
    theme_bw()+
  theme(plot.title=element_text(hjust=0.5),
        axis.title.y=element_blank())

h10 <- ggplot(trials_co2, aes(x = leafon)) +
  geom_histogram() + ggtitle("Leaves On") +
  xlab("Hours in the Year") + ylab("Frequency")+
    theme_bw()+
  theme(plot.title=element_text(hjust=0.5),
        axis.title.y=element_blank())

h11 <- ggplot(trials_co2, aes(x = leaffoff)) +
  geom_histogram() + ggtitle("Leaf Off") +
  xlab("Hours in the Year") + ylab("Frequency")+
    theme_bw()+
  theme(plot.title=element_text(hjust=0.5))
       # axis.title.y=element_blank())

ggarrange(h5, h6, h7, h8, h9, h10, h11, nrow = 3, ncol = 3)
```
#ecosys code
```{r}
#turn on for local run testing
directory<-setwd("C:/Erin/ecosys/cove")

years <- c(2022,2023)
plant_prefix <- "02010"
nonplant_prefix <- "03010"

all_plant <- list()
all_nonplant <- list()

for (year in years) {
  # Read plant file
  plant_file <- paste0(plant_prefix, year, "hc")
  plant_path <- file.path(directory, plant_file)  
  if (file.exists(plant_path)) {
    plant <- read.table(plant_path, quote = "\"", comment.char = "", stringsAsFactors = FALSE)
    names(plant) <- plant[1, ]
    plant <- plant[-1, ]
    plant$Year <- year
    all_plant[[as.character(year)]] <- plant
  }
  
  # Read non-plant file
  nonplant_file <- paste0(nonplant_prefix, year, "hc")
  nonplant_path <- file.path(directory, nonplant_file)
  if (file.exists(nonplant_path)) {
    nonplant <- read.table(nonplant_path, quote = "\"", comment.char = "", stringsAsFactors = FALSE)
    names(nonplant) <- nonplant[1, ]
    nonplant <- nonplant[-1, ]
    nonplant$Year <- year
    all_nonplant[[as.character(year)]] <- nonplant
  }
}

# Combine all years for each
plant_df <- bind_rows(all_plant)
nonplant_df <- bind_rows(all_nonplant)

# Convert numeric columns
plant_df <- plant_df %>%
  mutate(across(c(ECO_CO2_FLUX, CH4_FLUX), as.numeric))
plant_df <- plant_df %>%
  select(DOY, DATE, HOUR, ECO_CO2_FLUX, CH4_FLUX)
plant_df$DATE <- dmy(plant_df$DATE)
plant_df$Month <- month(plant_df$DATE)
plant_df <- plant_df %>%
  mutate(Year = year(DATE),
         Month2 = month.name[Month])
plant_df$MonthYear <- factor(
  paste(plant_df$Year, plant_df$Month2, sep = "-"),
  levels = unique(paste(plant_df$Year, plant_df$Month2, sep = "-")))

nonplant_df <- nonplant_df %>%
  mutate(across(c(ECO_CO2_FLUX, CH4_FLUX), as.numeric))
nonplant_df <- nonplant_df %>%
  select(DOY, DATE, HOUR, ECO_CO2_FLUX, CH4_FLUX)
nonplant_df$DATE <- dmy(nonplant_df$DATE)
nonplant_df$Month <- month(nonplant_df$DATE)
nonplant_df <- nonplant_df %>%
  mutate(Year = year(DATE),
         Month2 = month.name[Month])
nonplant_df$MonthYear <- factor(
  paste(nonplant_df$Year, nonplant_df$Month2, sep = "-"),
  levels = unique(paste(nonplant_df$Year, nonplant_df$Month2, sep = "-")))

plant_df <- plant_df %>%
  mutate(HOUR = factor(as.character(HOUR),
                 levels = c("5","6","7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17","18", "19","20", "21", "22")), Month = factor(Month, levels = month.name))
plant_df$ECO_CO2_FLUX <- plant_df$ECO_CO2_FLUX*-1
plant_df$CH4_FLUX <- plant_df$CH4_FLUX*-1

nonplant_df <- nonplant_df %>%
  mutate(HOUR = factor(as.character(HOUR),
                 levels = c("5","6","7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17","18", "19","20", "21", "22")), Month = factor(Month, levels = month.name))

nonplant_df$ECO_CO2_FLUX <- nonplant_df$ECO_CO2_FLUX*-1
nonplant_df$CH4_FLUX <- nonplant_df$CH4_FLUX*-1

#plants
df_means_plant_cove <- plant_df %>%
  mutate(
    DATE = as.Date(DATE),
    Year = year(DATE),
    Month = month(DATE)
  ) %>%
  filter(
    Month %in% 5:10,
    Year %in% c(2022, 2023) #compare to chamber years
  ) %>%
  group_by(Year) %>%
  summarise(
    n_CO2 = sum(!is.na(ECO_CO2_FLUX)),
    n_CH4 = sum(!is.na(CH4_FLUX)),
    mean_ECO_CO2_Flux = ifelse(n_CO2 > 0, mean(ECO_CO2_FLUX, na.rm = TRUE), NA),
    mean_CH4_Flux     = ifelse(n_CH4 > 0, mean(CH4_FLUX, na.rm = TRUE), NA),
    .groups = "drop")

```
#chamber code
```{r}
resp22 <- read_excel ("soilrespiration_data22.xlsx")
resp23 <- read_excel ("soilrespiration_data23.xlsx")
resp_full <- rbind(resp22, resp23)
resp_full$Timestamp_Begin <- ymd_hms(resp_full$Timestamp_Begin)
resp_full$DATE <- format(resp_full$Timestamp_Begin, "%Y-%m-%d")
resp_full$DOY <- yday(resp_full$Timestamp_Begin)

df_clean <- resp_full %>%
  separate(Chamber_ID, into = c("Month", "HOUR", "TypeRep"), sep = "_") %>%
  mutate(
    VegType = substr(TypeRep, 1, 1),   # O or V
    Rep     = substr(TypeRep, 2, 2)    # replicate number
  )
df_clean[df_clean < -9000] <- NA

#Don't group by hour= keep chamber replicatets
obs2 <- df_clean %>%
  select(Year, Month, DOY, HOUR, Timestamp_Begin, VegType, Flux_CO2, Flux_CH4)

obs2$MonthYear <- factor(
  paste(obs2$Year, obs2$Month, sep = "-"),
  levels = unique(paste(obs2$Year, obs2$Month, sep = "-")))
obs2 <- obs2 %>%
  mutate(Timestamp_Begin = ymd_hms(Timestamp_Begin),
         DATE = as.Date(Timestamp_Begin))
obs2$HOUR <- as.numeric(obs2$HOUR)

obs_veg <- obs2 %>% filter(VegType == "V")
obs_open <- obs2 %>% filter(VegType == "O")

obs_veg <- obs_veg %>%
  mutate(
    HOUR = as.numeric(HOUR),
    Month = factor(Month, levels = month.name))

obs_open <- obs_open %>%
  mutate(
    HOUR = as.numeric(HOUR),
    Month = factor(Month, levels = month.name))

obs_veg <- obs_veg %>%
  mutate(HOUR = factor(as.character(HOUR),
                 levels = c("5","6","7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17","18", "19","20", "21", "22")), Month = factor(Month, levels = month.name))

obs_open <- obs_open %>%
  mutate(HOUR = factor(as.character(HOUR),
                 levels = c("5","6","7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17","18", "19","20", "21", "22")), Month = factor(Month, levels = month.name))
```
# join mod and obs
```{r}
plant_obs_ecosys <- obs_veg %>%
  left_join(plant_df, by = c("DATE", "HOUR"))

plant_obs_ecosys <- plant_obs_ecosys %>%
mutate(YM = paste0(
      substr(Year.x, 3, 4), "-",
      substr(Month.x, 1, 3)))
plant_obs_ecosys$YM<-as.factor(plant_obs_ecosys$YM)

#fct_relevel broke for some reason
#plant_obs_ecosys <- plant_obs_ecosys %>%
#  mutate(YM=fct_relevel(YM,c("22-Jul","22-Aug","22-Sep","22-Oct","23-Apr","23-May","23-Jun","23-Jul","23-Aug","23-Sep","23-Oct")))

plant_obs_ecosys <- plant_obs_ecosys %>%
  mutate(YM = factor(YM,
      levels = c(
        "22-Jul","22-Aug","22-Sep","22-Oct",
        "23-Apr","23-May","23-Jun","23-Jul",
        "23-Aug","23-Sep","23-Oct")))

open_obs_ecosys <- obs_open %>%
  left_join(nonplant_df, by = c("DATE", "HOUR"))

open_obs_ecosys <- open_obs_ecosys %>%
mutate(YM = paste0(
      substr(Year.x, 3, 4), "-",
      substr(Month.x, 1, 3)))
open_obs_ecosys$YM<-as.factor(open_obs_ecosys$YM)

open_obs_ecosys <- open_obs_ecosys %>%
  mutate(YM = factor(YM,
      levels = c(
        "22-Jul","22-Aug","22-Sep","22-Oct",
        "23-Apr","23-May","23-Jun","23-Jul",
        "23-Aug","23-Sep","23-Oct")))

str(plant_obs_ecosys)

#RMSE
#cove using channel parameters= PLANTS
rmse(plant_obs_ecosys$Flux_CH4,plant_obs_ecosys$CH4_FLUX) #observed then model
rmse(plant_obs_ecosys$Flux_CO2,plant_obs_ecosys$ECO_CO2_FLUX) 

#cove using channel parameters= OPEN
rmse(open_obs_ecosys$Flux_CH4,open_obs_ecosys$CH4_FLUX)
rmse(open_obs_ecosys$Flux_CO2,open_obs_ecosys$ECO_CO2_FLUX)

#plot(open_obs_ecosys$ECO_CO2_FLUX)

```
#PLOTS
##CO2 Vegetation
```{r}
make_plot_CO2 <- function(df, title_label) {
  ggplot(df, aes(x = as.numeric(HOUR))) +
    # Observations: mean ± SE ribbon and line
    stat_summary(aes(y = Flux_CO2, color = "Observed"), 
                 fun = mean, geom = "line", size = 0.8) +
    stat_summary(aes(y = Flux_CO2, fill = "Observed"), 
                 fun.data = mean_se, geom = "ribbon", 
                 alpha = 0.3, color = NA) +
    # Model: line only
    stat_summary(aes(y = ECO_CO2_FLUX, color = "Modeled"), 
                 fun = mean, geom = "line", size = 0.8) +
    facet_grid(~YM, scales = "free_x", 
               space = "free_x") +
    coord_cartesian(clip = "off") +
    scale_x_continuous(breaks = c(6, 12)) +
   # scale_y_continuous(limits = c(25, 30), 
   #                    expand = c(0,0)) +
    scale_color_manual(name = "Source", 
                       values = c("Observed" = "black",
                                  "Modeled" = "red")) +
    scale_fill_manual(name = "Standard error", 
                      values = c("Observed" = "grey30",
                                 "Modeled" = "red")) +
    labs(x = "Hour", 
         y = expression(CO[2]~flux~(mu*mol~m^{-2}~s^{-1})),
         title = title_label) +
    theme_bw() +
    theme(text = element_text(family = "serif"),
      plot.title = element_text(hjust = 0.5, size = 14),
      strip.background = element_blank(),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      legend.position = "top",
      axis.title.x= element_blank(),
      axis.text.x = element_blank(),
      plot.margin = margin(10, 10, 20, 10),
      strip.text.x = element_text(margin = 
                                    margin(b = 5, t = 5)))}

#exclusing 2022 July because the only fully flooded month
plant_obs_ecosys2<-plant_obs_ecosys %>%
  filter(MonthYear.y != "2022-July")

p1_co2 <- make_plot_CO2(plant_obs_ecosys2, "Carbon Dixode | Vegetation")

#write.csv(plant_obs_ecosys2, "C:/Erin/ecosys/Cove/plant_obs_ecosys2.csv")
write.csv(plant_obs_ecosys2, "C:/Erin/ecosys/Cove/plant_obs_ecosys2_CHANNEL.csv")
```
##CO2 Non-Vegetation
```{r}
make_plot_CO2b <- function(df, title_label) {
  ggplot(df, aes(x = as.numeric(HOUR))) +
    # Observations: mean ± SE ribbon and line
    stat_summary(aes(y = Flux_CO2, color = "Observed", fill = "Observed"), 
                 fun = mean, geom = "line", size = 0.8) +
    stat_summary(aes(y = Flux_CO2, fill = "Observed"), 
                 fun.data = mean_se, geom = "ribbon", alpha = 0.3, color = NA) +
    # Model: line only
    stat_summary(aes(y = ECO_CO2_FLUX, color = "Modeled"), 
                 fun = mean, geom = "line", size = 0.8) +
    facet_grid(~YM, scales = "free_x", space = "free_x") +
     coord_cartesian(clip = "off") +
    scale_x_continuous(breaks = c(6, 12)) +
   # scale_y_continuous(limits = c(-5, 5), expand = c(0,0)) +
    scale_color_manual(name = "Source", 
                       values = c("Observed" = "black", "Modeled" = "red")) +
    scale_fill_manual(name = "Source", 
                      values = c("Observed" = "grey30", "Modeled" = "red")) +
    labs(x = "Hour", 
         y = expression(CO[2]~flux~(mu*mol~m^{-2}~s^{-1})),
         title = title_label) +
    theme_bw() +
    theme(text = element_text(family = "serif"),
      plot.title = element_text(hjust = 0.5, size = 14),   # center title
      strip.background = element_blank(),
      axis.text.x = element_blank(),
      axis.title.x = element_blank(),
      axis.title.y = element_blank(),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      legend.position = "top",
      plot.margin = margin(10, 10, 20, 10),
      strip.text.x = element_text(margin = 
                                    margin(b = 5, t = 5)))} 

open_obs_ecosys2<-open_obs_ecosys %>%
  filter(MonthYear.y != "2022-July")

p2_co2 <- make_plot_CO2b(open_obs_ecosys2, "Carbon Dioxide | No Vegetation")

write.csv(open_obs_ecosys2, "C:/Erin/ecosys/Cove/open_obs_ecosys2_CHANNEL.csv")

#write.csv(open_obs_ecosys2, "C:/Erin/ecosys/Cove/open_obs_ecosys2.csv")

ggarrange(p1_co2, p2_co2, nrow=2, common.legend = TRUE)
```
##Model
```{r}
plant_obs_ecosys$Year.x <- as.factor(plant_obs_ecosys$Year.x)
open_obs_ecosys$Year.x <- as.factor(open_obs_ecosys$Year.x)

# Fit regression model with hourly data frame
co2model1 <- lm(Flux_CO2 ~ ECO_CO2_FLUX, data = plant_obs_ecosys)
summary(co2model1)
# Extract slope and R2
coef(co2model1)
co2slope1 <- coef(co2model1)[2]
co2intercept1 <- coef(co2model1)[1] # not used
co2r21 <- summary(co2model1)$r.squared

# ONE line for ALL years
ggplot(plant_obs_ecosys, aes(x =ECO_CO2_FLUX, y=Flux_CO2, colour = Year.x)) + #year_plant = numerical
 geom_point() +
  ylim(-32,32)+
  xlim(-32,32)+
  geom_smooth(method = "lm",se = FALSE,color = "black")+
  theme_bw() +
  theme(axis.text.x = element_text(hjust = 1),
        plot.title = element_text(hjust=0.5))+
  labs(x = expression(CO[2]~"flux (µmol m"^-2~"s"^-1~") Modeled"),
       y = expression(CO[2]~"flux (µmol m"^-2~"s"^-1~") Observed"),
       title = "Carbon Dioxide in Cove (Hourly, Plants)",
       color = "Year",
       fill = "Year")+
  annotate("text", 
        x = Inf, y = -Inf, hjust = 1.1, vjust = -0.5,
        label = paste0("Slope = ", round(co2slope1, 2),
                          "\nR² = ", round(co2r21, 2)))

# Fit regression model with NON PLANT data frame
co2model2 <- lm(Flux_CO2 ~ ECO_CO2_FLUX, data = open_obs_ecosys)
# Extract slope and R2
coef(co2model2)
co2slope2 <- coef(co2model2)[2]
co2intercept2 <- coef(co2model2)[1] # not used
co2r22 <- summary(co2model2)$r.squared

# ONE line for ALL years
ggplot(open_obs_ecosys, aes(x =ECO_CO2_FLUX, y=Flux_CO2, colour = Year.x)) + #year_plant = numerical
 geom_point() +
  xlim(-13,20)+
  ylim(-13,20)+
 geom_smooth(method = "lm",se = FALSE,color = "black")+
  theme_bw() +
  theme(axis.text.x = element_text(hjust = 1),
        plot.title = element_text(hjust=0.5))+
  labs(x = expression(CO[2]~"flux (µmol m"^-2~"s"^-1~") Modeled"),
       y = expression(CO[2]~"flux (µmol m"^-2~"s"^-1~") Observed"),
       title = "Carbon Dioxide in Cove (Hourly, Open)",
       color = "Year",
       fill = "Year")+
  annotate("text", 
        x = Inf, y = -Inf, hjust = 1.1, vjust = -0.5,
        label = paste0("Slope = ", round(co2slope2, 2),
                          "\nR² = ", round(co2r22, 2)))
```
##CH4 Vegetation
```{r}
make_plot_CH4 <- function(df, title_label) {
  ggplot(df, aes(x = as.numeric(HOUR))) +
    # Observations: mean ± SE ribbon and line
    stat_summary(aes(y = Flux_CH4, color = "Observed", fill = "Observed"), 
                 fun = mean, geom = "line", size = 0.8) +
    stat_summary(aes(y = Flux_CH4, fill = "Observed"), 
                 fun.data = mean_se, geom = "ribbon", alpha = 0.3, color = NA) +
    # Model: line only
    stat_summary(aes(y = CH4_FLUX, color = "Modeled"), 
                 fun = mean, geom = "line", size = 0.8) +
    facet_grid(~YM, scales = "free_x", space = "free_x") +
     coord_cartesian(clip = "off") +
    scale_x_continuous(breaks = c(0, 6, 12)) +
    scale_y_continuous(limits = c(0, 1), 
                       expand = c(0,0)) +
    scale_color_manual(name = "Source", 
                       values = c("Observed" = "black", "Modeled" = "red")) +
    scale_fill_manual(name = "Source", 
                      values = c("Observed" = "grey30", "Modeled" = "red")) +
    labs(x = "Hour", 
         y = expression(CH[4]~flux~(mu*mol~m^{-2}~s^{-1})),
         title = title_label) +
    theme_bw() +
    theme(text = element_text(family = "serif"),
      plot.title = element_text(hjust = 0.5, 
                                size = 14),   # center title
      strip.background = element_blank(),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      legend.position = "top",
      plot.margin = margin(10, 10, 20, 10),
      strip.text.x = element_text(margin = 
                                    margin(b = 5, t = 5)))}
plant_obs_ecosys2<-plant_obs_ecosys %>%
  filter(MonthYear.y != "2022-July")
p1_cH4 <- make_plot_CH4(plant_obs_ecosys2, "Methane | Vegetation")

```

##CH4 Non-Vegetation
```{r}
make_plot_Ch4b <- function(df, title_label) {
  ggplot(df, aes(x = as.numeric(HOUR))) +
    # Observations: mean ± SE ribbon and line
    stat_summary(aes(y = Flux_CH4, color = "Observed", fill = "Observed"), 
                 fun = mean, geom = "line", size = 0.8) +
    stat_summary(aes(y = Flux_CH4, fill = "Observed"), 
                 fun.data = mean_se, geom = "ribbon", alpha = 0.3, color = NA) +
    stat_summary(aes(y = CH4_FLUX, color = "Modeled"), 
                 fun = mean, geom = "line", size = 0.8) +
    facet_grid(~YM, scales = "free_x", 
               space = "free_x") +
     coord_cartesian(clip = "off") +
    scale_x_continuous(breaks = c(0, 6, 12)) +
    scale_y_continuous(limits = c(0, 2.5), expand = c(0,0)) +
    scale_color_manual( 
                       values = c("Observed" = "black", "Modeled" = "red")) +
    scale_fill_manual(
                      values = c("Observed" = "grey30", "Modeled" = "red")) +
    labs(x = "Hour", 
         y = expression(CH[4]~flux~(mu*mol~m^{-2}~s^{-1})),
         title = title_label) +
    theme_bw() +
    theme(text = element_text(family = "serif"),
      plot.title = element_text(hjust = 0.5, size = 14),   # center title
      strip.background = element_blank(),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      axis.title.y=element_blank(),
      legend.position = "top",
      plot.margin = margin(10, 10, 20, 10),
      strip.text.x = element_text(margin = 
                                    margin(b = 5, t = 5)))}
open_obs_ecosys2<-open_obs_ecosys %>%
  filter(MonthYear.y != "2022-July")

#p2_ch4b <- make_plot_Ch4b(open_obs_ecosys2," Methane | No Vegetation")
p2_ch4b <- make_plot_Ch4b(open_obs_ecosys2," Methane | No Vegetation")

ggarrange(p1_co2,p2_co2, p1_cH4, p2_ch4b, ncol=2,nrow=2, common.legend = TRUE, labels="AUTO")
```
#before/after channel 
```{r}
#library("ggh4x")#label nesting in ggplot
#This is with the good data!
open_original <-read.csv("open_obs_ecosys2.csv")
plant_original <-read.csv("plant_obs_ecosys2.csv")
#this is with the channel parameters
open_channel <-read.csv("open_obs_ecosys2_CHANNEL.csv")
plant_channel <-read.csv("plant_obs_ecosys2_CHANNEL.csv")

open_original <- open_original %>%
  mutate(
    YM = ifelse(YM == "23-Apr", "23-Ap", YM),
    YM = ifelse(YM == "23-May", "23-Ma", YM),
    YM = factor( YM,levels = c(
        "22-Jul","22-Aug","22-Sep","22-Oct",
        "23-Ap","23-Ma","23-Jun","23-Jul",
        "23-Aug","23-Sep","23-Oct")))

plant_original <- plant_original %>%
  mutate(
    YM = ifelse(YM == "23-Apr", "23-Ap", YM),
    YM = ifelse(YM == "23-May", "23-Ma", YM),
    YM = factor( YM,levels = c(
        "22-Jul","22-Aug","22-Sep","22-Oct",
        "23-Ap","23-Ma","23-Jun","23-Jul",
        "23-Aug","23-Sep","23-Oct")))

open_channel <- open_channel %>%
  mutate(
    YM = ifelse(YM == "23-Apr", "23-Ap", YM),
    YM = ifelse(YM == "23-May", "23-Ma", YM),
    YM = factor( YM,levels = c(
        "22-Jul","22-Aug","22-Sep","22-Oct",
        "23-Ap","23-Ma","23-Jun","23-Jul",
        "23-Aug","23-Sep","23-Oct")))

plant_channel <- plant_channel %>%
  mutate(
    YM = ifelse(YM == "23-Apr", "23-Ap", YM),
    YM = ifelse(YM == "23-May", "23-Ma", YM),
    YM = factor( YM,levels = c(
        "22-Jul","22-Aug","22-Sep","22-Oct",
        "23-Ap","23-Ma","23-Jun","23-Jul",
        "23-Aug","23-Sep","23-Oct")))

p1_CO2 <- ggplot() +
  stat_summary(data = plant_original,
               aes(x = as.numeric(HOUR), y = Flux_CO2,
                   color = "Observed"), fun = mean,
               geom = "line", size = 0.8) +
  stat_summary(data = plant_original,
               aes(x = as.numeric(HOUR), y = Flux_CO2,
                   fill = "Observed"),
               fun.data = mean_se, geom = "ribbon",
               alpha = 0.3, color = NA) +
  ## --- Modeled with site-specifc parrameters= Cove specific
  stat_summary(data = plant_original,
               aes(x = as.numeric(HOUR), y = ECO_CO2_FLUX,
                   color = "Modeled (After: Site-specific)"),
               fun = mean, geom = "line", size = 0.8) +
  ## --- Modeled using Channel parameters
  stat_summary(data = plant_channel,
               aes(x = as.numeric(HOUR), y =ECO_CO2_FLUX,
                   color = "Modeled (Before: Main pool values)"),
               fun = mean, geom = "line", size = 0.8) +
  facet_grid(~YM, scales = "free_x", space = "free_x") +
  coord_cartesian(clip = "off") +
  scale_x_continuous(breaks = c(6, 12)) +
  scale_color_manual(
    name = "Source",
    values = c("Observed" = "black",
               "Modeled (Before: Main pool values)" = "red",
               "Modeled (After: Site-specific)"  = "blue")) +
  scale_fill_manual(
    name = "Standard error",
    values = c("Observed" = "grey30")) +
  labs(x = "Hour",
       y = expression(CO[2]~flux~(mu*mol~m^{-2}~s^{-1})),
       title = "Vegetation") +
  theme_bw() +
  theme(text = element_text(size = 12,family = "serif"),
    panel.grid = element_blank(),
    legend.position = "top",
    #plot.margin = margin(t = 15, r = 5, b = 5, l = 5),
    plot.margin = margin(30, 10, 15, 10),
    strip.background = element_blank(),
    strip.placement = "outside",
    strip.text.x = element_text(size=9,  margin = margin(t = 6, b = 6)),
  strip.background.x.top = element_rect(
    fill = "grey90",
    color = "black",
    linewidth = 0.6),
  strip.text.x.top = element_text(
    size = 9),
    #face = "bold"),
  ## MONTH strip (no box)
  strip.background.x = element_blank(),
    axis.title.x = element_blank(),
    axis.text.x = element_blank(),
    plot.title = element_text(hjust = 0.5, size = 14))
#non plants CO2
p2_CO2 <- ggplot() +
  stat_summary(data = open_original,
               aes(x = as.numeric(HOUR), y = Flux_CO2,
                   color = "Observed"), fun = mean,
               geom = "line", size = 0.8) +
  stat_summary(data = open_original,
               aes(x = as.numeric(HOUR), y = Flux_CO2,
                   fill = "Observed"),
               fun.data = mean_se, geom = "ribbon",
               alpha = 0.3, color = NA) +
  stat_summary(data = open_original,
               aes(x = as.numeric(HOUR), y = ECO_CO2_FLUX,
                   color = "Modeled (After: Site-specific)"),
               fun = mean, geom = "line", size = 0.8) +
  stat_summary(data = open_channel,
               aes(x = as.numeric(HOUR), y = ECO_CO2_FLUX,
                   color = "Modeled (Before: Main pool values)"),
               fun = mean, geom = "line", size = 0.8) +
  facet_grid(~YM, scales = "free_x", space = "free_x") +
  coord_cartesian(clip = "off") +
  scale_x_continuous(breaks = c(6, 12)) +
  scale_color_manual(
    name = "Source",
    values = c("Observed" = "black",
               "Modeled (Before: Main pool values)" = "red",
               "Modeled (After: Site-specific)"  = "blue")) +
  scale_fill_manual(
    name = "Standard error",
    values = c("Observed" = "grey30")) +
  labs(x = "Hour",
       y = expression(CO[2]~flux~(mu*mol~m^{-2}~s^{-1})),
       title = "No Vegetation") +
  theme_bw() +
  theme(text = element_text(size = 12,family = "serif"),
    panel.grid = element_blank(),
    legend.position = "top",
    #plot.margin = margin(t = 15, r = 5, b = 5, l = 5),
    plot.margin = margin(30, 10, 15, 10),
    strip.background = element_blank(),
    strip.placement = "outside",
    strip.text.x = element_text(size=9,  margin = margin(t = 6, b = 6)),
  strip.background.x.top = element_rect(
    fill = "grey90",
    color = "black",
    linewidth = 0.6),
  strip.text.x.top = element_text(
    size = 9),
    #face = "bold"),
  ## MONTH strip (no box)
  strip.background.x = element_blank(),
    axis.title.x = element_blank(),
    axis.text.x = element_blank(),
    axis.title.y=element_blank(),
    plot.title = element_text(hjust = 0.5, size = 14))

p1_CH4 <- ggplot() +
  stat_summary(data = plant_original,
               aes(x = as.numeric(HOUR), y = Flux_CH4,
                   color = "Observed"), fun = mean,
               geom = "line", size = 0.8) +
  stat_summary(data = plant_original,
               aes(x = as.numeric(HOUR), y = Flux_CH4,
                   fill = "Observed"),
               fun.data = mean_se, geom = "ribbon",
               alpha = 0.3, color = NA) +
  stat_summary(data = plant_original,
               aes(x = as.numeric(HOUR), y = CH4_FLUX,
                   color = "Modeled (After: Site-specific)"),
               fun = mean, geom = "line", size = 0.8) +
  stat_summary(data = plant_channel,
               aes(x = as.numeric(HOUR), y = CH4_FLUX,
                   color = "Modeled (Before: Main pool values)"),
               fun = mean, geom = "line", size = 0.8) +
  facet_grid(~YM, scales = "free_x", space = "free_x") +
  coord_cartesian(clip = "off") +
  scale_x_continuous(breaks = c(12)) +
  scale_color_manual(
    name = "Source",
    values = c("Observed" = "black",
               "Modeled (Before: Main pool values)" = "red",
               "Modeled (After: Site-specific)"  = "blue")) +
  scale_fill_manual(
    name = "Standard error",
    values = c("Observed" = "grey30")) +
  labs(x = "Hour",
       y = expression(CH[4]~flux~(mu*mol~m^{-2}~s^{-1})))+
      # title = "Methane | Vegetation") +
  theme_bw() +
  theme(text = element_text(size = 12,family = "serif"),
    strip.background = element_blank(),
    panel.grid = element_blank(),
    legend.position = "top",
    #plot.margin = margin(t = 15, r = 5, b = 5, l = 5),
    plot.margin = margin(30, 10, 15, 10),
    strip.text.x = element_blank(),
    strip.background.x = element_blank(),
    axis.text.x.top = element_blank(),
    axis.title.x.top = element_blank(),
    axis.ticks.x.top = element_blank(),
   # axis.title.x = element_blank(),
    #axis.text.x = element_blank(),
    plot.title = element_text(hjust = 0.5, size = 14))

p2_CH4 <- ggplot() +
  stat_summary(data = open_original,
               aes(x = as.numeric(HOUR), y = Flux_CH4,
                   color = "Observed"), fun = mean,
               geom = "line", size = 0.8) +
  stat_summary(data = open_original,
               aes(x = as.numeric(HOUR), y = Flux_CH4,
                   fill = "Observed"),
               fun.data = mean_se, geom = "ribbon",
               alpha = 0.3, color = NA) +
  stat_summary(data = open_original,
               aes(x = as.numeric(HOUR), y = CH4_FLUX,
                   color = "Modeled (After: Site-specific)"),
               fun = mean, geom = "line", size = 0.8) +
  stat_summary(data = open_channel,
               aes(x = as.numeric(HOUR), y = CH4_FLUX,
                   color = "Modeled (Before: Main pool values)"),
               fun = mean, geom = "line", size = 0.8) +
  facet_grid(~YM, scales = "free_x", space = "free_x") +
  coord_cartesian(clip = "off") +
  scale_x_continuous(breaks = c(12)) +
  scale_color_manual(
    name = "Source",
    values = c("Observed" = "black",
               "Modeled (Before: Main pool values)" = "red",
               "Modeled (After: Site-specific)"  = "blue")) +
  scale_fill_manual(
    name = "Standard error",
    values = c("Observed" = "grey30")) +
  labs(x = "Hour",
       y = expression(CH[4]~flux~(mu*mol~m^{-2}~s^{-1})))+
      # title = "Methane | No Vegetation") +
  theme_bw() +
  theme(text = element_text(size = 12,family = "serif"),
    strip.background = element_blank(),
    panel.grid = element_blank(),
   # plot.margin = margin(t = 15, r = 5, b = 5, l = 5),
    strip.text.x = element_blank(),
    strip.background.x = element_blank(),
    legend.position = "top",
    #axis.title.x = element_blank(),
    axis.text.x.top = element_blank(),
    axis.title.x.top = element_blank(),
    axis.ticks.x.top = element_blank(),
    #axis.text.x = element_blank(),
    axis.title.y = element_blank(),
    plot.margin = margin(30, 10, 15, 10),
    plot.title = element_text(hjust = 0.5, size = 14))
```
#figure 6
```{r}
figure6<-ggarrange(
  p1_CO2, p2_CO2,
  p1_CH4, p2_CH4,
  ncol = 2, nrow = 2,
  common.legend = TRUE,
  labels = "AUTO"
)

ggsave(
  "figure6.tiff",
  plot = figure6,
  width = 3200,
  height = 2000,
  units = "px",
  dpi = 300,
  compression = "lzw")
```
##Model
```{r}
# Fit regression model with hourly data frame
ch4model1 <- lm(Flux_CH4 ~ CH4_FLUX, data = plant_obs_ecosys)
summary(ch4model1)
# Extract slope and R2
coef(ch4model1)
ch4slope1 <- coef(ch4model1)[2]
ch4intercept1 <- coef(ch4model1)[1] # not used
ch4r21 <- summary(ch4model1)$r.squared

# ONE line for ALL years
ggplot(plant_obs_ecosys, aes(x =CH4_FLUX, y=Flux_CH4, colour = Year.x)) + #year_plant = numerical
 geom_point() +
  ylim(-0.1,8.5)+
  xlim(-0.1,8.5)+
 geom_smooth(method = "lm",se = FALSE,color = "black")+
  theme_bw() +
  theme(axis.text.x = element_text(hjust = 1),
        plot.title = element_text(hjust=0.5))+
  labs(x = expression(CH[4]~"flux (µmol m"^-2~"s"^-1~") Modeled"),
       y = expression(CH[4]~"flux (µmol m"^-2~"s"^-1~") Observed"),
       title = "Methane in Cove (Hourly, Plants)",
       color = "Year",
       fill = "Year")+
  annotate("text", 
        x = 8, y = 2, hjust = 1.1, vjust = -0.5,
        label = paste0("Slope = ", round(ch4slope1, 2),
                          "\nR² = ", round(ch4r21, 2)))

# Fit regression model with OPEN data frame
ch4model2 <- lm(Flux_CH4 ~ CH4_FLUX, data = open_obs_ecosys)
# Extract slope and R2
coef(ch4model2)
ch4slope2 <- coef(ch4model2)[2]
ch4intercept2 <- coef(ch4model2)[1] # not used
ch4r22 <- summary(ch4model2)$r.squared

# ONE line for ALL years
ggplot(open_obs_ecosys, aes(x =CH4_FLUX, y=Flux_CH4, colour = Year.x)) + #year_plant = numerical
 geom_point() +
  ylim(-1,4.5)+
  xlim(-1,4.5)+
 geom_smooth(method = "lm",se = FALSE,color = "black")+
  theme_bw() +
  theme(axis.text.x = element_text(hjust = 1),
        plot.title = element_text(hjust=0.5))+
  labs(x = expression(CH[4]~"flux (µmol m"^-2~"s"^-1~") Modeled"),
       y = expression(CH[4]~"flux (µmol m"^-2~"s"^-1~") Observed"),
       title = "Methane in Cove (Hourly, Open)",
       color = "Year",
       fill = "Year")+
  annotate("text", 
        x = Inf, y = -Inf, hjust = 1.1, vjust = -0.5,
        label = paste0("Slope = ", round(ch4slope2, 2),
                          "\nR² = ", round(ch4r22, 2)))
```
#_____________
#CHANNEL PARAMS
#ecosys code
```{r}
break
setwd("C:/Erin/ecosys/cove/Cove_using_Channel-params")
#turn on for local run testing
directory2<-setwd("C:/Erin/ecosys/cove/Cove_using_Channel-params")

years <- c(2022,2023)
plant_prefix <- "02010"
nonplant_prefix <- "03010"

all_plant <- list()
all_nonplant <- list()

for (year in years) {
  # Read plant file
  plant_file <- paste0(plant_prefix, year, "hc")
  plant_path <- file.path(directory2, plant_file)  
  if (file.exists(plant_path)) {
    plant <- read.table(plant_path, quote = "\"", comment.char = "", stringsAsFactors = FALSE)
    names(plant) <- plant[1, ]
    plant <- plant[-1, ]
    plant$Year <- year
    all_plant[[as.character(year)]] <- plant
  }
  
  # Read non-plant file
  nonplant_file <- paste0(nonplant_prefix, year, "hc")
  nonplant_path <- file.path(directory2, nonplant_file)
  if (file.exists(nonplant_path)) {
    nonplant <- read.table(nonplant_path, quote = "\"", comment.char = "", stringsAsFactors = FALSE)
    names(nonplant) <- nonplant[1, ]
    nonplant <- nonplant[-1, ]
    nonplant$Year <- year
    all_nonplant[[as.character(year)]] <- nonplant
  }
}

# Combine all years for each
plant_df <- bind_rows(all_plant)
nonplant_df <- bind_rows(all_nonplant)

# Convert numeric columns
plant_df <- plant_df %>%
  dplyr::mutate(across(c(ECO_CO2_FLUX, CH4_FLUX), as.numeric))
plant_df <- plant_df %>%
  select(DOY, DATE, HOUR, ECO_CO2_FLUX, CH4_FLUX)
plant_df$DATE <- dmy(plant_df$DATE)
plant_df$Month <- month(plant_df$DATE)
plant_df <- plant_df %>%
  mutate(Year = year(DATE),
         Month2 = month.name[Month])
plant_df$MonthYear <- factor(
  paste(plant_df$Year, plant_df$Month2, sep = "-"),
  levels = unique(paste(plant_df$Year, plant_df$Month2, sep = "-")))

nonplant_df <- nonplant_df %>%
  mutate(across(c(ECO_CO2_FLUX, CH4_FLUX), as.numeric))
nonplant_df <- nonplant_df %>%
  select(DOY, DATE, HOUR, ECO_CO2_FLUX, CH4_FLUX)
nonplant_df$DATE <- dmy(nonplant_df$DATE)
nonplant_df$Month <- month(nonplant_df$DATE)
nonplant_df <- nonplant_df %>%
  mutate(Year = year(DATE),
         Month2 = month.name[Month])
nonplant_df$MonthYear <- factor(
  paste(nonplant_df$Year, nonplant_df$Month2, sep = "-"),
  levels = unique(paste(nonplant_df$Year, nonplant_df$Month2, sep = "-")))

plant_df <- plant_df %>%
  mutate(HOUR = factor(as.character(HOUR),
                 levels = c("5","6","7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17","18", "19","20", "21", "22")), Month = factor(Month, levels = month.name))
plant_df$ECO_CO2_FLUX <- plant_df$ECO_CO2_FLUX*-1
plant_df$CH4_FLUX <- plant_df$CH4_FLUX*-1

nonplant_df <- nonplant_df %>%
  mutate(HOUR = factor(as.character(HOUR),
                 levels = c("5","6","7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17","18", "19","20", "21", "22")), Month = factor(Month, levels = month.name))

nonplant_df$ECO_CO2_FLUX <- nonplant_df$ECO_CO2_FLUX*-1
nonplant_df$CH4_FLUX <- nonplant_df$CH4_FLUX*-1

```
#chamber code
```{r}
resp22 <- read_excel ("soilrespiration_data22.xlsx")
resp23 <- read_excel ("soilrespiration_data23.xlsx")
resp_full <- rbind(resp22, resp23)
resp_full$Timestamp_Begin <- ymd_hms(resp_full$Timestamp_Begin)
resp_full$DATE <- format(resp_full$Timestamp_Begin, "%Y-%m-%d")
resp_full$DOY <- yday(resp_full$Timestamp_Begin)

df_clean <- resp_full %>%
  separate(Chamber_ID, into = c("Month", "HOUR", "TypeRep"), sep = "_") %>%
  mutate(
    VegType = substr(TypeRep, 1, 1),   # O or V
    Rep     = substr(TypeRep, 2, 2)    # replicate number
  )
df_clean[df_clean < -9000] <- NA

#Don't group by hour= keep chamber replicatets
obs2 <- df_clean %>%
  select(Year, Month, DOY, HOUR, Timestamp_Begin, VegType, Flux_CO2, Flux_CH4)

obs2$MonthYear <- factor(
  paste(obs2$Year, obs2$Month, sep = "-"),
  levels = unique(paste(obs2$Year, obs2$Month, sep = "-")))
obs2 <- obs2 %>%
  mutate(Timestamp_Begin = ymd_hms(Timestamp_Begin),
         DATE = as.Date(Timestamp_Begin))
obs2$HOUR <- as.numeric(obs2$HOUR)

obs_veg <- obs2 %>% filter(VegType == "V")
obs_open <- obs2 %>% filter(VegType == "O")

obs_veg <- obs_veg %>%
  mutate(
    HOUR = as.numeric(HOUR),
    Month = factor(Month, levels = month.name))

obs_open <- obs_open %>%
  mutate(
    HOUR = as.numeric(HOUR),
    Month = factor(Month, levels = month.name))

obs_veg <- obs_veg %>%
  mutate(HOUR = factor(as.character(HOUR),
                 levels = c("5","6","7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17","18", "19","20", "21", "22")), Month = factor(Month, levels = month.name))

obs_open <- obs_open %>%
  mutate(HOUR = factor(as.character(HOUR),
                 levels = c("5","6","7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17","18", "19","20", "21", "22")), Month = factor(Month, levels = month.name))
```
# join mod and obs
```{r}
plant_obs_ecosys <- obs_veg %>%
  left_join(plant_df, by = c("DATE", "HOUR"))

plant_obs_ecosys <- plant_obs_ecosys %>%
mutate(YM = paste0(
      substr(Year.x, 3, 4), "-",
      substr(Month.x, 1, 3)))
plant_obs_ecosys$YM<-as.factor(plant_obs_ecosys$YM)
plant_obs_ecosys <- plant_obs_ecosys %>%
  mutate(YM=fct_relevel(YM,c("22-Jul","22-Aug","22-Sep","22-Oct","23-Apr","23-May","23-Jun","23-Jul","23-Aug","23-Sep","23-Oct")))

open_obs_ecosys <- obs_open %>%
  left_join(nonplant_df, by = c("DATE", "HOUR"))

open_obs_ecosys <- open_obs_ecosys %>%
mutate(YM = paste0(
      substr(Year.x, 3, 4), "-",
      substr(Month.x, 1, 3)))
open_obs_ecosys$YM<-as.factor(open_obs_ecosys$YM)
open_obs_ecosys <- open_obs_ecosys %>%
  mutate(YM=fct_relevel(YM,c("22-Jul","22-Aug","22-Sep","22-Oct","23-Apr","23-May","23-Jun","23-Jul","23-Aug","23-Sep","23-Oct")))


#plot(open_obs_ecosys$ECO_CO2_FLUX)
```
#PLOTS
##CO2 Vegetation
```{r}
make_plot_CO2_chan <- function(df, title_label) {
  ggplot(df, aes(x = as.numeric(HOUR))) +
    # Observations: mean ± SE ribbon and line
    stat_summary(aes(y = Flux_CO2, color = "Observed"), 
                 fun = mean, geom = "line", size = 0.8) +
    stat_summary(aes(y = Flux_CO2, fill = "Observed"), 
                 fun.data = mean_se, geom = "ribbon", 
                 alpha = 0.3, color = NA) +
    # Model: line only
    stat_summary(aes(y = ECO_CO2_FLUX, color = "Modeled"), 
                 fun = mean, geom = "line", size = 0.8) +
    facet_grid(~YM, scales = "free_x", 
               space = "free_x") +
    coord_cartesian(clip = "off") +
    scale_x_continuous(breaks = c(6, 12)) +
   # scale_y_continuous(limits = c(25, 30), 
   #                    expand = c(0,0)) +
    scale_color_manual(name = "Source", 
                       values = c("Observed" = "black",
                                  "Modeled" = "red")) +
    scale_fill_manual(name = "Standard error", 
                      values = c("Observed" = "grey30",
                                 "Modeled" = "red")) +
    labs(x = "Hour", 
         y = expression(CO[2]~flux~(mu*mol~m^{-2}~s^{-1})),
         title = title_label) +
    theme_bw() +
    theme(
      plot.title = element_text(hjust = 0.5, size = 14),
      strip.background = element_blank(),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      legend.position = "top",
      axis.title.x= element_blank(),
      axis.text.x = element_blank(),
      plot.margin = margin(10, 10, 20, 10),
      strip.text.x = element_text(margin = 
                                    margin(b = 5, t = 5)))}

plant_obs_ecosys2<-plant_obs_ecosys %>%
  filter(MonthYear.y != "2022-July")

p1_co2_chan <- make_plot_CO2_chan(plant_obs_ecosys2, "Carbon Dixode | Vegetation")

```
##CO2 Non-Vegetation
```{r}
make_plot_CO2b_chan <- function(df, title_label) {
  ggplot(df, aes(x = as.numeric(HOUR))) +
    # Observations: mean ± SE ribbon and line
    stat_summary(aes(y = Flux_CO2, color = "Observed", fill = "Observed"), 
                 fun = mean, geom = "line", size = 0.8) +
    stat_summary(aes(y = Flux_CO2, fill = "Observed"), 
                 fun.data = mean_se, geom = "ribbon", alpha = 0.3, color = NA) +
    # Model: line only
    stat_summary(aes(y = ECO_CO2_FLUX, color = "Modeled"), 
                 fun = mean, geom = "line", size = 0.8) +
    facet_grid(~YM, scales = "free_x", space = "free_x") +
     coord_cartesian(clip = "off") +
    scale_x_continuous(breaks = c(6, 12)) +
   # scale_y_continuous(limits = c(-5, 5), expand = c(0,0)) +
    scale_color_manual(name = "Source", 
                       values = c("Observed" = "black", "Modeled" = "red")) +
    scale_fill_manual(name = "Source", 
                      values = c("Observed" = "grey30", "Modeled" = "red")) +
    labs(x = "Hour", 
         y = expression(CO[2]~flux~(mu*mol~m^{-2}~s^{-1})),
         title = title_label) +
    theme_bw() +
    theme(
      plot.title = element_text(hjust = 0.5, size = 14),   # center title
      strip.background = element_blank(),
      axis.text.x = element_blank(),
      axis.title.x = element_blank(),
      axis.title.y = element_blank(),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      legend.position = "top",
      plot.margin = margin(10, 10, 20, 10),
      strip.text.x = element_text(margin = 
                                    margin(b = 5, t = 5)))} 

p2_co2_chan <- make_plot_CO2b_chan(open_obs_ecosys, "Carbon Dioxide | No Vegetation")

ggarrange(p1_co2_chan, p2_co2_chan, nrow=2, common.legend = TRUE)
```
##Model
```{r}
plant_obs_ecosys$Year.x <- as.factor(plant_obs_ecosys$Year.x)
open_obs_ecosys$Year.x <- as.factor(open_obs_ecosys$Year.x)
# Fit regression model with hourly data frame
co2model1 <- lm(Flux_CO2 ~ ECO_CO2_FLUX, data = plant_obs_ecosys)
summary(co2model1)
# Extract slope and R2
coef(co2model1)
co2slope1 <- coef(co2model1)[2]
co2intercept1 <- coef(co2model1)[1] # not used
co2r21 <- summary(co2model1)$r.squared

# ONE line for ALL years
ggplot(plant_obs_ecosys, aes(x =ECO_CO2_FLUX, y=Flux_CO2, colour = Year.x)) + #year_plant = numerical
 geom_point() +
  ylim(-32,32)+
  xlim(-32,32)+
  geom_smooth(method = "lm",se = FALSE,color = "black")+
  theme_bw() +
  theme(axis.text.x = element_text(hjust = 1),
        plot.title = element_text(hjust=0.5))+
  labs(x = expression(CO[2]~"flux (µmol m"^-2~"s"^-1~") Modeled"),
       y = expression(CO[2]~"flux (µmol m"^-2~"s"^-1~") Observed"),
       title = "Carbon Dioxide in Cove (Hourly, Plants)",
       color = "Year",
       fill = "Year")+
  annotate("text", 
        x = Inf, y = -Inf, hjust = 1.1, vjust = -0.5,
        label = paste0("Slope = ", round(co2slope1, 2),
                          "\nR² = ", round(co2r21, 2)))

# Fit regression model with NON PLANT data frame
co2model2 <- lm(Flux_CO2 ~ ECO_CO2_FLUX, data = open_obs_ecosys)
# Extract slope and R2
coef(co2model2)
co2slope2 <- coef(co2model2)[2]
co2intercept2 <- coef(co2model2)[1] # not used
co2r22 <- summary(co2model2)$r.squared

# ONE line for ALL years
ggplot(open_obs_ecosys, aes(x =ECO_CO2_FLUX, y=Flux_CO2, colour = Year.x)) + #year_plant = numerical
 geom_point() +
  xlim(-13,20)+
  ylim(-13,20)+
 geom_smooth(method = "lm",se = FALSE,color = "black")+
  theme_bw() +
  theme(axis.text.x = element_text(hjust = 1),
        plot.title = element_text(hjust=0.5))+
  labs(x = expression(CO[2]~"flux (µmol m"^-2~"s"^-1~") Modeled"),
       y = expression(CO[2]~"flux (µmol m"^-2~"s"^-1~") Observed"),
       title = "Carbon Dioxide in Cove (Hourly, Open)",
       color = "Year",
       fill = "Year")+
  annotate("text", 
        x = Inf, y = -Inf, hjust = 1.1, vjust = -0.5,
        label = paste0("Slope = ", round(co2slope2, 2),
                          "\nR² = ", round(co2r22, 2)))
```
##CH4 Vegetation
```{r}
make_plot_CH4_chan <- function(df, title_label) {
  ggplot(df, aes(x = as.numeric(HOUR))) +
    # Observations: mean ± SE ribbon and line
    stat_summary(aes(y = Flux_CH4, color = "Observed", fill = "Observed"), 
                 fun = mean, geom = "line", size = 0.8) +
    stat_summary(aes(y = Flux_CH4, fill = "Observed"), 
                 fun.data = mean_se, geom = "ribbon", alpha = 0.3, color = NA) +
    # Model: line only
    stat_summary(aes(y = CH4_FLUX, color = "Modeled"), 
                 fun = mean, geom = "line", size = 0.8) +
    facet_grid(~YM, scales = "free_x", space = "free_x") +
     coord_cartesian(clip = "off") +
    scale_x_continuous(breaks = c(0, 6, 12)) +
    scale_y_continuous(limits = c(0, 1), 
                       expand = c(0,0)) +
    scale_color_manual(name = "Source", 
                       values = c("Observed" = "black", "Modeled" = "red")) +
    scale_fill_manual(name = "Source", 
                      values = c("Observed" = "grey30", "Modeled" = "red")) +
    labs(x = "Hour", 
         y = expression(CH[4]~flux~(mu*mol~m^{-2}~s^{-1})),
         title = title_label) +
    theme_bw() +
    theme(
      plot.title = element_text(hjust = 0.5, 
                                size = 14),   # center title
      strip.background = element_blank(),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      legend.position = "top",
      plot.margin = margin(10, 10, 20, 10),
      strip.text.x = element_text(margin = 
                                    margin(b = 5, t = 5)))}
plant_obs_ecosys2<-plant_obs_ecosys %>%
  filter(MonthYear.y != "2022-July")
p1_cH4_chan <- make_plot_CH4_chan(plant_obs_ecosys2, "Methane | Vegetation")

```

##CH4 Non-Vegetation
```{r}
make_plot_Ch4b_chan <- function(df, title_label) {
  ggplot(df, aes(x = as.numeric(HOUR))) +
    # Observations: mean ± SE ribbon and line
    stat_summary(aes(y = Flux_CH4, color = "Observed", fill = "Observed"), 
                 fun = mean, geom = "line", size = 0.8) +
    stat_summary(aes(y = Flux_CH4, fill = "Observed"), 
                 fun.data = mean_se, geom = "ribbon", alpha = 0.3, color = NA) +
    stat_summary(aes(y = CH4_FLUX, color = "Modeled"), 
                 fun = mean, geom = "line", size = 0.8) +
    facet_grid(~YM, scales = "free_x", 
               space = "free_x") +
     coord_cartesian(clip = "off") +
    scale_x_continuous(breaks = c(0, 6, 12)) +
    scale_y_continuous(limits = c(0, 2.5), expand = c(0,0)) +
    scale_color_manual( 
                       values = c("Observed" = "black", "Modeled" = "red")) +
    scale_fill_manual(
                      values = c("Observed" = "grey30", "Modeled" = "red")) +
    labs(x = "Hour", 
         y = expression(CH[4]~flux~(mu*mol~m^{-2}~s^{-1})),
         title = title_label) +
    theme_bw() +
    theme(
      plot.title = element_text(hjust = 0.5, size = 14),   # center title
      strip.background = element_blank(),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      axis.title.y=element_blank(),
      legend.position = "top",
      plot.margin = margin(10, 10, 20, 10),
      strip.text.x = element_text(margin = 
                                    margin(b = 5, t = 5)))}
open_obs_ecosys2<-open_obs_ecosys %>%
  filter(MonthYear.y != "2022-July")

p2_ch4b_chan <- make_plot_Ch4b(open_obs_ecosys2, " Methane | No Vegetation")

ggarrange(p1_co2_chan,p2_co2_chan, p1_cH4_chan, p2_ch4b_chan, ncol=2,nrow=2, common.legend = TRUE)
```
##Model
```{r}
break
# Fit regression model with hourly data frame
ch4model1 <- lm(Flux_CH4 ~ CH4_FLUX, data = plant_obs_ecosys)
summary(ch4model1)
# Extract slope and R2
coef(ch4model1)
ch4slope1 <- coef(ch4model1)[2]
ch4intercept1 <- coef(ch4model1)[1] # not used
ch4r21 <- summary(ch4model1)$r.squared

# ONE line for ALL years
ggplot(plant_obs_ecosys, aes(x =CH4_FLUX, y=Flux_CH4, colour = Year.x)) + #year_plant = numerical
 geom_point() +
  ylim(-0.1,8.5)+
  xlim(-0.1,8.5)+
 geom_smooth(method = "lm",se = FALSE,color = "black")+
  theme_bw() +
  theme(axis.text.x = element_text(hjust = 1),
        plot.title = element_text(hjust=0.5))+
  labs(x = expression(CH[4]~"flux (µmol m"^-2~"s"^-1~") Modeled"),
       y = expression(CH[4]~"flux (µmol m"^-2~"s"^-1~") Observed"),
       title = "Methane in Cove (Hourly, Plants)",
       color = "Year",
       fill = "Year")+
  annotate("text", 
        x = 8, y = 2, hjust = 1.1, vjust = -0.5,
        label = paste0("Slope = ", round(ch4slope1, 2),
                          "\nR² = ", round(ch4r21, 2)))

# Fit regression model with OPEN data frame
ch4model2 <- lm(Flux_CH4 ~ CH4_FLUX, data = open_obs_ecosys)
# Extract slope and R2
coef(ch4model2)
ch4slope2 <- coef(ch4model2)[2]
ch4intercept2 <- coef(ch4model2)[1] # not used
ch4r22 <- summary(ch4model2)$r.squared

# ONE line for ALL years
ggplot(open_obs_ecosys, aes(x =CH4_FLUX, y=Flux_CH4, colour = Year.x)) + #year_plant = numerical
 geom_point() +
  ylim(-1,4.5)+
  xlim(-1,4.5)+
 geom_smooth(method = "lm",se = FALSE,color = "black")+
  theme_bw() +
  theme(axis.text.x = element_text(hjust = 1),
        plot.title = element_text(hjust=0.5))+
  labs(x = expression(CH[4]~"flux (µmol m"^-2~"s"^-1~") Modeled"),
       y = expression(CH[4]~"flux (µmol m"^-2~"s"^-1~") Observed"),
       title = "Methane in Cove (Hourly, Open)",
       color = "Year",
       fill = "Year")+
  annotate("text", 
        x = Inf, y = -Inf, hjust = 1.1, vjust = -0.5,
        label = paste0("Slope = ", round(ch4slope2, 2),
                          "\nR² = ", round(ch4r22, 2)))
```
